### ISSUE TITLE
Output raw data

### ISSUE THREAD

**Issue by Norbo11** [benfred/py-spy#106]
Hi,

There are many use-cases which require the collection of raw profiling information produced by py-spy, other than display by the built-in top-like view.

I was wondering whether there are any plans on implementing such a feature? This was also requested in #35.

Thanks,
Norbert

**Comment by aparamon** [comment]
Please see https://github.com/benfred/py-spy/pull/74 (and tangentially related https://github.com/benfred/py-spy/pull/76)

**Comment by benfred** [comment]
with v0.2.0 you can specify speedscope/raw format as an option to the record process - let me know if this works for you all
