### ISSUE TITLE
py27 win64 version on PyPI

### ISSUE THREAD

**Issue by PhilReinhold** [benfred/py-spy#11]
`pip install py-spy` yields `Could not find a version that satisfies the requirement py-spy`. 'I see a py27-win32 version and a py35/6-win64 version on [PyPI](https://pypi.org/project/py-spy/#files) but no py27 win64. If this is not supported perhaps the readme could reflect this.

**Comment by benfred** [comment]
Right now all the different 64 bit versions install the same rust binary (which can handle multiple different versions of python).  This should work with python 2.7 on windows, you just need to get the py-spy binary installed, which can be done in the short term via ```cargo install py-spy``` (if you have rust).

 This is mainly an issue of how I'm packaging up windows wheels right now - on osx/linux there are 'py2.py3-none' wheels that support multiple platforms, but I haven't yet gotten that going on windows. It shouldn't be hard to do though, I'll try to get it going tomorrow

**Comment by benfred** [comment]
Attempted to fix this here: https://github.com/benfred/py-spy/commit/6c2706867f9c13a2e5f9f3acc6c9e47f890094e7 

Appveyor *should* build a single generic wheel that can be installed for multiple different versions of python on windows

**Comment by benfred** [comment]
Going ```pip install py-spy``` should work on windows with a 64 bit python2 install now
