### ISSUE TITLE
Use as a library

### ISSUE THREAD

**Issue by sophiebits-humu** [benfred/py-spy#110]
Similar to https://github.com/benfred/py-spy/pull/74 – for building infrastructure on top of py-spy it would be nice if there was a supported programmatic API for using py-spy functionality from a larger Rust program.

(In my case, I was thinking of taking occasional samples from running processes and logging them to a central database for "global profiling" analysis across many machines and a long time period.)

**Comment by benfred** [comment]
Thanks! I think this is a great idea, and just exposing as a rust library isn't a big change at all. 

You can use py-spy 0.1.11 as a library with that last PR (#126). The exposed API is pretty basic and only covers the core use case of getting samples from a target process, and doesn't include things like the flamegraph/console code . The API's here might change a bit until we hit a 1.0 release,  but by limiting the exposed public API I'm hoping to minimize breaking changes to anyone that might use this crate.

I've created a sample repo https://github.com/benfred/pyspy_example that shows how to use this, and there is some very basic documentation on the exposed API's here https://docs.rs/py-spy/0.1.11/py_spy/

I've also been thinking about exposing a python api w/ py03 (and even wrote up a [blog post](http://www.benfrederickson.com/writing-python-extensions-in-rust-using-pyo3/) about the approach last year) - but exposing py-spy as a rust library will let anyone who is interested build the python bindings themselves using the steps in that post.
