### ISSUE TITLE
Filter lines?

### ISSUE THREAD

**Issue by guettli** [benfred/py-spy#111]
It would be very great if you could filter the lines.

I am not interested in the bug-free stdlib or framework lines. I would like to see my buggy lines.

I use python-hunter[1] for tracing sometimes. It has a flexible way to filter lines.

What do you think about filtering the lines?

1: https://github.com/ionelmc/python-hunter

**Comment by xmo-odoo** [comment]
Seems unnecessary with raw output having been merged: raw flamegraph data (the kind flamegraph.pl takes as input) is one stack per line (with a count at the end), and a stack is a ;-separated list of frames. So should be easy enough to filter out "uninteresting" frames.

**Comment by guettli** [comment]
ok, solved. Thank you.
