### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by akhramov** [benfred/py-spy#112]
Hi, thanks for your awesome application, I really love it.

FreeBSD is a somewhat popular system among developers and it would be nice to have it supported.

Do you have any objections so far? If not, keep reading.

As far as I can tell, this application relies on few third-party libs which do not support FreeBSD yet.
So, if we were making a checklist it would be like this:

- [ ]   Support FreeBSD in  [rbspy/proc-maps](https://github.com/rbspy/proc-maps).
**Status:** PR was created (rbspy/proc-maps#3).
- [ ]   Support FreeBSD in  [luser/read-process-memory](https://github.com/luser/read-process-memory).
**Status:** Support was added in luser/read-process-memory#7, however, I'd wait for luser/read-process-memory#10 for better ergonomics.
- [ ] Support FreeBSD here, in py-spy

Am I missing something? What do you think?

**Comment by benfred** [comment]
Awesome! This would be great to add.

I think you've done most of the hard work here already (proc-maps/read-process-memory changes). Most of the remaining changes here should be in the 'remoteprocess' subcrate here.

Minimally we're looking at adding code to:
- [ ] lock the remote process (probably can use ptrace like in linux?)
- [ ] get the executable name of the process

Also - it would be great if we could also add code to do this (but isn't necessary to get basic python profiling working on freebsd):
- [ ] list threads of the remote process
- [ ] get if a thread is running or not
- [ ] lock an individual thread

I haven't ever used freebsd - but I think the tricky thing here is that there isn't procfs that we can use reliably (please correct me if I'm wrong =).

**Comment by akhramov** [comment]
Thanks, Ben.

It shouldn't be a lot of hassle to implement all of this. In fact, I think that `ptrace(2)`  would handle most of the cases.

Alright, I'm working on the `remoteprocess` subcrate. Will get back with the PR. :smiley:

**Comment by benfred** [comment]
Awesome! 
 
I thought about this a little more today - and I think there is some more work that needs to happen though. We'll need to get CI setup so that I don't accidentally break this in a future change, also we need to disable the native extension code otherwise this won't build easily.

I've been planning on adding a feature flag for the native extension code (also needed to re-enable the ARM build again https://github.com/benfred/py-spy/issues/89), so you won't need to implement that code for freebsd. I will get this going this weekend and update here once it's done.

Finally, do you have any suggestions on how best to distribute w/ freedbsd? I don't think that there is a binary wheel format that will work with freebsd - making ```pip install py-spy``` probably a non-starter. :(

**Comment by akhramov** [comment]
Cool, worry not, I will setup Cirrus-backed CI, the same I've set up for the proc-maps crate:
https://github.com/rbspy/proc-maps/pull/3/files

As for distribution... I will dig into this. If there's no appropriate wheel format, I think I'm going to create a FreeBSD port. How does that sound to you?

**Comment by benfred** [comment]
I've fixed up the ARM build, and I believe that native extension code should be disabled for FreeBSD now (which should simplify things quite a bit).

For distribution,  I looked into it quickly and I don't think we can distribute binary wheels. I was also thinking about just uploading compiled binaries to the releases page on github might work out pretty well too (like what rbspy does https://github.com/rbspy/rbspy/releases ).

**Comment by akhramov** [comment]
Uh, thanks! Sorry for the huge delay. PR Is up here #131.

Besides review, we need to settle things down with dependencies. I put details in the PR.

**Comment by drozdowsky** [comment]
I see that FreeBSD support is merged (huge thanks btw!), can we have new release on PyPy so I can install py-spy on my workstation? 

Thanks!

**Comment by akhramov** [comment]
@drozdowsky py-spy will likely be distributed in binary form from the GH releases page, as @benfred suggested above.

We can create put py-spy to the ports tree as well, though...

@benfred does rbspy automate the build process or they build binaries manually? 
If you need me to build the release artefact manually, just ping me.

**Comment by benfred** [comment]
PyPi doesn't support binary freebsd wheels - so we won't be able to install via pip like @akhramov mentioned.

I've set up cirrus to upload a tarball to the GH releases page automatically in https://github.com/benfred/py-spy/pull/135 - and from testing it out there is a freebsd tarball here: https://github.com/benfred/py-spy/releases/download/v0.2.0.dev3/py-spy-v0.2.0.dev3-x86_64-freebsd.tar.gz 

You should be able to install it on your workstation from there (download the tarball, but the py-spy binary it contains somewhere on your path. It's a pre-release version, but should work pretty well.
