### ISSUE TITLE
Drop down to root on macOS, just like rbspy

### ISSUE THREAD

**Issue by pquentin** [benfred/py-spy#116]
rbspy has this great feature where you can just use sudo on macOS, and [rbspy will drop root privileges when executing the script](https://rbspy.github.io/using-rbspy/#record-by-executing-the-process-through-rbspy). This should allow to just run "sudo py-spy ..." instead of having to first find the PID, and then run py-spy with sudo.

This is where it seems to be implemented in rbspy: https://github.com/rbspy/rbspy/blob/806ace599aa8e7de99c2134935c0fe1047bc6803/src/main.rs#L164-L179

PS: Thanks for py-spy! It's a great project, and the recent release is even more useful with the removed perl dependency. 💚

**Comment by benfred** [comment]
Thanks! I'm glad py-spy is coming in useful for you.

I added some code to drop root permissions in #127 - will be in the next release.

**Comment by pquentin** [comment]
Thank you! That works great. This is another awesome improvement. 👏
