### ISSUE TITLE
Mark time spent in 'poll()' as idle

### ISSUE THREAD

**Issue by benfred** [benfred/py-spy#13]
[From HN](https://news.ycombinator.com/item?id=17928883):

> Also, it would be nice to somehow eliminate time spent in poll() from the results. I'm profiling a server process and 99.9% of the time is spent in a poll function. Perhaps there could be an option to disregard time spent in system calls rather than user code. Most of the time I'm interested in profiling only user code.

**Comment by benfred** [comment]
We will want better idle detection eventually, but in the meantime adding poll() to here https://github.com/benfred/py-spy/blob/master/src/stack_trace.rs#L67 seems like a good quick fix

**Comment by willstott101** [comment]
First of all, great project. Secondly in our framework the vast majority of a process' time is spent in the `poll` function from zmq. `.../dist-packages/zmq/sugar/poll.py:99`. I don't know much about this problem-space from a technical POV but I assume it would be near-impossible to get it right by default every time. Perhaps a commandline option to specify functions that are known to be interesting/uninteresting could be nice?

Users would at least know about the possibility of false-positives if they're setting the values themselves.

`--include mypkg/*`
`--exclude poll()` 
`--exclude zmq/*/poll()`

**Comment by balta2ar** [comment]
@benfred Could you please update the HN link? it requires login now.

**Comment by benfred** [comment]
@willstott101 I think it's a good idea to add some configuration options to exclude certain patterns - it's impossible for me to get this right 100% of the time, and I don't get enough information from just reading the pyinterpreterstate to figure out if the thread is actually idle or not

I'm thinking of adding a config file instead of (so that you don't need to add the command line options everytime). Like if there is a .pyspyrc file in the current directory or your home directory then load exclusions from it, so that this config will persist across sessions. 

I'm also working on some new visualization code that should let you filter/zoom in easier.

In the meantime I've marked the poll function from zmq/tornado/gevent/asyncore as being idle: https://github.com/benfred/py-spy/commit/23c0796ec6addf972ac7d8eb4ef393409cc64860 . Will be in the next release

@balta2ar I updated the hn link =) didn't realize it was a reply link

**Comment by willstott101** [comment]
Great, thanks very much. Although I'm thinking about using this as a subprocess in which case the commandline options make a lot of sense... perhaps both would be doable <3

I might have a hack about trying to create something for this issue if you're interested - although I wouldn't rely on myself to produce anything releasable from the off.

Do you have any idea what that config might look like? Those glob-style things I showed with a special meaning for brackets to denote a function name I quite liked.

**Comment by nziebart** [comment]
I would like to understand this issue a bit more. I am seeing the following functions being marked as `active`:

- `time.sleep()` (for some reason the `sleep` function itself doesn't appear in the stacktrace, the last frame is the calling function with the line number corresponding to where `sleep` is called)
- [this line](https://github.com/tornadoweb/tornado/blob/branch4.5/tornado/ioloop.py#L863) in tornado (it looks like there is logic [here](https://github.com/benfred/py-spy/blob/master/src/stack_trace.rs#L76) that is supposed to handle this, but again the `poll` function doesn't show up in the stacktrace, only the calling function does)

I guess my main question is why these functions don't actually appear in the stack trace (thus eluding any attempt to special case them)

**Comment by EmreAtes** [comment]
Another function can be added to the default ignore list
* The `wait` function in `eventlet` [here](https://github.com/eventlet/eventlet/blob/master/eventlet/hubs/poll.py#L71)
Also, a configuration file would be very helpful for people without a rust compiler.

**Comment by benfred** [comment]
@nziebart : we don't track into native code yet,  so we show the time spent as being in the line of python code that called the native extension (rather than the native extension itself).  For both of your cases I believe the functions are native code, so you're hitting this issue:  https://github.com/benfred/py-spy/issues/2

I've also created an issue to track the config file https://github.com/benfred/py-spy/issues/51 . I'm still not sure the best syntax for the exclusion, though the glob style @willstott101 proposed seems like it could work pretty well
