### ISSUE TITLE
Provide ARM binaries

### ISSUE THREAD

**Issue by DavidVentura** [benfred/py-spy#130]
Hi
I am trying to debug an issue that seems to be only happening on a raspberry pi, I was quite surprised to see that pypi does not allow wheels for ARM.
Would it be possible for you to provide ARM binaries when you make a release?

**Comment by DavidVentura** [comment]
So, in these 10 minutes I downloaded/installed rust, an arm crosscompiler, tried to build, failed ( saying `   | ---------------- not an extern crate passed with `--extern`), switched to nightly, re-built and now my binary needs glibc `2.29` while I'm at `2.24` in debian stretch

**Comment by benfred** [comment]
I've [updated our travis ci to upload binaries](https://github.com/benfred/py-spy/commit/1c8280d9a38933f70c7148d66d84d7290526e23b) whenever I tag a release - and travis was already cross compiling an ARM version

With these changes, you can now download an arm build here: https://github.com/benfred/py-spy/releases/tag/v0.2.0.dev3 .  Let me know if this works for you =)

**Comment by DavidVentura** [comment]
Excellent! Thank you!
