### ISSUE TITLE
osx build remoteprocess

### ISSUE THREAD

**Issue by phxa1** [benfred/py-spy#137]
```
error[E0599]: no method named `copy_address` found for type `u32` in the current scope
  --> /Users/phxa1/.cargo/registry/src/github.com-1ecc6299db9ec823/remoteprocess-0.1.0/src/osx/mod.rs:90:22
   |
90 |         Ok(self.task.copy_address(addr, buf)?)
   |                      ^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by bluetech** [comment]
This happens on Linux too. I believe the problem is with the `Cargo.lock`, because it happens when I tried `cargo install` (which uses `Cargo.lock`) but doesn't happen with `cargo build --release`.

**Comment by phxa1** [comment]
> This happens on Linux too. I believe the problem is with the `Cargo.lock`, because it happens when I tried `cargo install` (which uses `Cargo.lock`) but doesn't happen with `cargo build --release`.
I am new in rust, so just change the source code, it works.

```rust
impl super::ProcessMemory for Process {
    fn read(&self, addr: usize, buf: &mut [u8]) -> Result<(), Error> {
        let handle: ProcessHandle = self.task.try_into()?;
        Ok(handle.copy_address(addr, buf)?)
        // Ok(self.task.copy_address(addr, buf)?)
    }
}
```

**Comment by benfred** [comment]
I think this issue was caused because going ```cargo install py-spy``` was bringing in benfred-read-process-memory 0.1.4  - which was compatible with py-spy v0.1.11 . That version had some API incompatabilities, and I've yanked it from crates.io (and replaced with benfred-read-process-memor v0.2.0). This should work now - sorry about this!
