### ISSUE TITLE
error when python program is given in stdin

### ISSUE THREAD

**Issue by anntzer** [benfred/py-spy#140]
Admittedly a slightly obscure case, but practical if one wants to profile a single slow command:
```
$ py-spy -- python - <<EOF
import time; time.sleep(10)
EOF

Error: Failed to get process executable name. Check that the process is running.
Reason: No such file or directory (os error 2)
```
(Yes, I know about `python -c ...` but sometimes the thing doesn't fit in a single line, e.g. with loops.)
Happens both with 0.1.11 and with 0.2.0dev3.

Thanks for the nice work :)

**Comment by benfred** [comment]
py-spy uses stdin for keyboard input on the console viewer - so the input you're piping in on stdin is getting sent to py-spy rather than the profiled python command, which I think is why it's not working.

I don't really see a way around this unfortunately ...

**Comment by anntzer** [comment]
Good point, I guess I can work around that case by connecting separately to the profiled program via --pid.
