### ISSUE TITLE
freebsd issue when profiling network connection

### ISSUE THREAD

**Issue by benfred** [benfred/py-spy#147]
Even with the read_process_memory fix  from #145, I hit another issue on freebsd when trying to profile a python script that is downloading a file over the network. The profiled process in this case is killed, when it works fine when not run under py-spy.

The profiled script is:

```python
from tempfile import NamedTemporaryFile
import os
try:
    from urllib.request import urlretrieve
except ImportError:
    from urllib import urlretrieve

f = NamedTemporaryFile()
urlretrieve('https://github.com/benfred/recommender_data/releases/download/v1.0/lastfm_360k.hdf5', f.name)
```
@akhramov  any ideas on this?

**Comment by benfred** [comment]
This also happens on a simpler version of the script without the progress bar:

```python
from tempfile import NamedTemporaryFile
import os
try:
    from urllib.request import urlretrieve
except ImportError:
    from urllib import urlretrieve

f = NamedTemporaryFile()
urlretrieve('https://github.com/benfred/recommender_data/releases/download/v1.0/lastfm_360k.hdf5', f.name)
```

**Comment by akhramov** [comment]
For me, the child process fails with

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 22] Invalid argument
```

I'm confused...

**Comment by akhramov** [comment]
Well!

Under the hood, `connect(2)` syscall is interrupted and returns `EINTR` code (4). 

Looks like the recent python interpreters have a bug somewhere in socket connection routines.
Have a look here: https://bugs.python.org/issue23618

The attached test case (connect_eintr.py) fails on FreeBSD, but works on Linux just fine.

I'm not 100% sure, though... Why errno ends up to be 22? I have no clue, sorry.

**Comment by benfred** [comment]
Nice work in tracking this down! 

I just confirmed that your patch does indeed prevent this issue from happening. I'd like to see it backported to older versions of python too. Let me know if I can be of any assistance here.

I believe the 'Failed to suspend process' problem was just another symptom of https://github.com/benfred/py-spy/issues/146 - with that fix in place I don't see that behaviour anymore.

**Comment by akhramov** [comment]
Alright, the PR has been merged, we can expect this problem to be resolved in the near future.

Just a couple of things to consider here.

1. Python2.7 did not handle interrupted syscalls in the socket module. Therefore, the issue is going to be reproducible.

2. I'm worried about OSX. I'm not sure whether mach calls interrupt BSD syscalls (such as `select`, `poll`). If it is the case we might have the same bug on OSX as well.

I don't have a mac at time, but if you have a chance to test this yourself, I have the repro. Just try to profile the code below.

```
import socket

ADDRESS = ('1.1.1.1', 80)

print("Press CTRL + c to stop")
while True:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect(ADDRESS)
```

**Comment by benfred** [comment]
Awesome! Glad the PR got merged.

This issue is limited to FreeBSD: I ran the test script on OSX and it works fine (and I'm also pretty sure I would have noticed before if this was a problem). On OSX we're not using ptrace and instead are using mach calls like vm_read_overwrite to read memory and task_suspend/task_resume to pause/unpause the process - which I think is why this isn't happening.

**Comment by benfred** [comment]
I added an extra check for people that are attaching to an already running process in that last commit. The idea is that you need to acknowledge that you know about this problem by setting an environment variable before we will let you attach to an already running process. While newer versions of python aren't affected, we don't know the version until we've already attached to the process (and potentially caused this problem).

Resolving this issue, since I don't think there is anything more we can really do here.
