### ISSUE TITLE
--flame option: No output and premature termination

### ISSUE THREAD

**Issue by guettli** [benfred/py-spy#152]
If I call py-spy like this:

`py-spy --flame profile.svg -- python foo.py`

Then the stdout of `foo.py` is not visible.

And scripts stops after roughly two seconds.

My script needs roughly twenty seconds to run.

**Comment by benfred** [comment]
In the stable release, there is a 'duration' commandline parameter that defaults to 2 seconds. Try sampling with ```py-spy --flame profile.svg --duration 50 -- python foo.py``` to increase this. I'm pretty sure this is the problem you are hitting.

A bunch of other people have also found this confusing too (https://github.com/benfred/py-spy/issues/44 / https://github.com/benfred/py-spy/issues/93) - so I've changed the default duration to be unlimited here https://github.com/benfred/py-spy/pull/136 . 

This change is in the latest dev release ```pip install py-spy==0.2.0.dev4```. The commandline parameters have changed slightly, so with the new version you need to go: ```py-spy record -o profile.svg -- python foo.svg```
