### ISSUE TITLE
"pip install py-spy" gets error on my Windows 10 Intel machine

### ISSUE THREAD

**Issue by jrmelom** [benfred/py-spy#165]
when I try "pip install py-spy", I get the errors:

  ERROR: Could not find a version that satisfies the requirement py-spy (from versions: none)
ERROR: No matching distribution found for py-spy

going into verbose mode gives many messages of the form:
Skipping link: none of the wheel's tags match: <here I get a variety of names>.
    some examples of unmatched tags include:
        cp36-cp36m-win32
        cp35-cp35m-win_amd64

**Comment by benfred** [comment]
py-spy only supports 64-bit python on windows right now: https://github.com/benfred/py-spy/issues/31 , I'm guessing you're running an x86 build of python instead of an x86_64 version?

**Comment by jrmelom** [comment]
Thanks.  Re-installed 3.7.4 making sure I used the x86_64 installer and the py-spy install worked.
