### ISSUE TITLE
README URL pointing to flamegraph page invalid

### ISSUE THREAD

**Issue by swayson** [benfred/py-spy#181]
![image](https://user-images.githubusercontent.com/1834241/66704138-c6fdd500-ed19-11e9-82c0-ef1f90670443.png)

Browser: firefox
Branch: master
Check on: 2019-10-12
Line 37: [flame graph](http://www.brendangregg.com/flamegraphs.html)

**Comment by benfred** [comment]
That looks like a SSL error - and the link in the README is http only (not https). Loading over http works fine for me, but trying for https fails with the error you saw. 

Are you using the https everywhere extension or something similar?

**Comment by swayson** [comment]
Ah, yes thanks for that. Turned out it was https everywhere that cause the ssl errors
