### ISSUE TITLE
Native profiling with --nonblocking

### ISSUE THREAD

**Issue by marmoute** [benfred/py-spy#189]
I we could get both I would be very happy. (I assume there is some reason it is hard, but let's at least document it).
It would be quite useful for us.

(For the record, we use py-spy to profile the C and Rust extensions of Mercurial)

**Comment by benfred** [comment]
I don't think this is possible unfortunately =( On linux we're using libunwind-ptrace for getting the native stack, which requires locking the thread with a ptrace attach.
