### ISSUE TITLE
Line numbers wrong with Python 3.8

### ISSUE THREAD

**Issue by martinstein** [benfred/py-spy#190]
After upgrading my local project to Python 3.8, the line numbers that py-spy reports are about 3-8 times too high (difference varies). This affects both the flamegraph and the speedscope output.

**Environment:**
Python 3.8.0
Windws 10 Pro, Version 10.0.18362 Build 18362
py-spy==0.3.0 (but I believe it affects earlier versions, too)

Note: This situation occurs when the program that is analyzed is running on Python 3.8 and it's independent of the Python environment that I start py-spy from. To clarify:

* Profiled code runs in: 3.7, py-spy runs in: 3.7 -> line numbers OK
* Profiled code runs in: 3.7, py-spy runs in: 3.8 -> line numbers OK
* Profiled code runs in: 3.8, py-spy runs in: 3.7 -> line numbers *wrong*
* Profiled code runs in: 3.8, py-spy runs in: 3.8 -> line numbers *wrong*

**Comment by benfred** [comment]
I haven't managed to replicate this - but after looking into that code I realized there is a bug there that could be causing this issue =( I have a fix in #196 that I hope will fix this issue.

**Comment by Nudin** [comment]
I have the same issue.
To test #196 I cloned the repo, and ran `python ./setup.py install --user` – and the line numbers are still of by a factor of nearly 100.

**Comment by martinstein** [comment]
Yup, I can confirm that with the latest release v0.3.1 this issue still exists. @benfred  Is there some information from my Python environment that I can give you that might help you in narrowing this down?

**Comment by benfred** [comment]
#208 fixes this issue - will be the in the next release

**Comment by benfred** [comment]
Fix is in v0.3.2

**Comment by martinstein** [comment]
Yup, can confirm that line numbers work perfectly again. Thanks!
