### ISSUE TITLE
Speedscope format doesn't seem to respect -F

### ISSUE THREAD

**Issue by tavianator** [benfred/py-spy#201]
When using `py-spy record -f speedscope`, the `-F` flag seems to make no difference.  Functions are still split into separate chunks by line number.  Additionally the line number isn't even visible in the sandwich view, which makes it a bit hard to use.

**Comment by benfred** [comment]
Thanks for the bug report!  #202 changes to not include line numbers in speedscope profiles when the -F flag is used.

The line number not being visible in sandwich view issue is being tracked https://github.com/jlfwong/speedscope/issues/247 right now

**Comment by benfred** [comment]
Fix is in 0.3.1
