### ISSUE TITLE
Running py-spy without capturing any output?

### ISSUE THREAD

**Issue by Detry322** [benfred/py-spy#217]
Hey there!

I love your tool - I often use it to profile my python programs using the `record` feature, specifying a profiling output file with `-o`. When I run in this mode, it would be really nice if it didn't capture the output of my program, since sometimes the output is something I need to be watching for diagnostic purposes, or it's being piped into another program. Can you add an option to preserve the output of the program being profiled?

**Comment by benfred** [comment]
Thanks for the suggestion! I've added the option for the 'record' mode here https://github.com/benfred/py-spy/pull/222 to display stderr/stdout - and I've made it the default. You can get the old behaviour by passing a ``--capture``` flag to py-spy.

**Comment by benfred** [comment]
Change is in v0.3.3
