### ISSUE TITLE
Make '--output' optional

### ISSUE THREAD

**Issue by Nudin** [benfred/py-spy#229]
When I use py-spy I often forget the output parameter. I also often don't care much about the filename and often it would be nice to know the date of the profile.
We could solve all three "issues" by making the output parameter optional. If not given when calling the profile option py-spy could write the output in a file called '<program_name>-<timestamp>'. (For the case of sampling an already running process we could ether use the pid instead of the program name or query the name of the executable)

Would you accept a PR for this? I would be interested in doing this as a 'first patch' to get some rust-exercise and first step into this awesome tool.

**Comment by Nudin** [comment]
@benfred: *ping* – I wouldn't like to start if I don't know your interested in a PR.

**Comment by benfred** [comment]
Thanks @nudin - I'm definitely interested! Sorry for the delayed response.

Can you make sure to set the extension for the filename appropriately base off the file format (like '.svg' for flamegraph, '.json' for speedscope, '.txt' for raw) ?

**Comment by benfred** [comment]
Fixed by #229
