### ISSUE TITLE
py-spy: command not found

### ISSUE THREAD

**Issue by bikhilall** [benfred/py-spy#232]
Py-spy command not found after fresh installation on ubuntu.
```
$ pip install py-spy
Collecting py-spy
  Using cached https://files.pythonhosted.org/packages/8e/a7/ab45c9ee3c4654edda3efbd6b8e2fa4962226718a7e3e3be6e3926bf3617/py_spy-0.3.3-py2.py3-none-manylinux1_x86_64.whl
Installing collected packages: py-spy
Successfully installed py-spy-0.3.3


$ py-spy top --python simulator.py 
py-spy: command not found

```

**Comment by RustingSword** [comment]
Generally this means pip installation path is not in your `$PATH`.

You can run `pip show py-spy` to find out where `py-spy` is installed:
```bash
$ pip show py-spy
Name: py-spy
Version: 0.3.3
...
Location: /SOME_PYTHON_ENV/lib/python3.6/site-packages
```
`py-spy` command most likely can be found in `/SOME_PYTHON_ENV/bin`, and add this to `$PATH` should fix the problem.

**Comment by benfred** [comment]
Which pip are you using? There was an issue with  pip 20.0.x that would cause this: https://github.com/benfred/py-spy/issues/218
