### ISSUE TITLE
Clarify difference between {%own,%total} and {owntime,totaltime}?

### ISSUE THREAD

**Issue by anntzer** [benfred/py-spy#24]
Naively, one would expect that %own is just owntime/(total time spent profiling the program) and similarly %total=totaltime/(total time spent profiling the program), but this is clearly not the case (for example sorting by %own and by owntime give different results).

Could you clarify what %own actually means?

Thanks!

**Comment by benfred** [comment]
The percentages are the current usage (in the last second), whereas the time is the cumulative time since starting to profile.  There is a brief explanation in the help screen.

I did this to sort of mimic top - where the %CPU is the current cpu usage, and TIME+ is the total spent time.

**Comment by szeitlin** [comment]
I have this same question and still don't quite understand (top doesn't have anything called own).
