### ISSUE TITLE
support uwsgi

### ISSUE THREAD

**Issue by benfred** [benfred/py-spy#25]
Currently profiling [uwsgi](https://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html) fails with a 'no python binary could be found' error.

**Comment by benfred** [comment]
Basic support for uwsgi should be in the 0.1.6 release

**Comment by marc1n** [comment]
In py-spy 0.1.10 and uWSGI 2.0.18 (installed in virtualenv) with Python 2.7.15+ I have following problem:

$ sudo env PATH=$PATH py-spy --pid 361
Error: Failed to find python version from target process

**Comment by AivanF** [comment]
Hi! Having same problem with Gunicorn :( Is there any solution?
