### ISSUE TITLE
Clarification for the behavior of concurrent target memory reading

### ISSUE THREAD

**Issue by fillest** [benfred/py-spy#26]
Hello.
As I've understood from "How does py-spy work?" readme section, the memory of the target process is read with `process_vm_readv` on the fly - while the process continues to run. According to `man`, `process_vm_readv` is not atomic itself, and if a sampling operation is performed through multiple reads, the whole operation is not atomic as the overall interpreter state memory potentially continues to change between readings. Is it handled somehow in py-spy, how or how does it affect accuracy if not? I think it's worth mentioning in "How does py-spy work?"

**Comment by benfred** [comment]
I agree it's probably worth talking about a bit more in the README.

We're not pausing the process here, and this does occasionally cause sampling errors. If you run the flame graph code it will report the number of errors at the end (and the top view will report the error rate if [it goes beyond 1%](https://github.com/benfred/py-spy/blob/master/src/console_viewer.rs#L136)).  This happens infrequently enough that it shouldn't affect the output that much though.

Julia Evans wrote a great blog post talking about this trade off with rbspy:
https://jvns.ca/blog/2018/01/15/should-i-pause-a-ruby-process-to-collect-its-stack/

**Comment by fillest** [comment]
Oh, good to know. Interesting results.

**Comment by benfred** [comment]
Last commit adds a section to the FAQ.
