### ISSUE TITLE
Pyspy exited with code 1 (when using docker-compose up)

### ISSUE THREAD

**Issue by johnmzz** [benfred/py-spy#272]
Dear developers,

When running Pyspy along with other containers through docker-compose up, I'm receiving messages of Pyspy exiting with code 1. 

```
(base) user$ docker-compose up
Starting redis                ... done
Starting backend_pyspy_1 ... done
Starting rabbitmq             ... done
Starting mongo                ... done
Starting backend_predict_worker_1 ... done
Starting backend_train_worker_1   ... done
Starting backend_master_1         ... done
Attaching to redis, rabbitmq, backend_pyspy_1, mongo, backend_master_1, backend_predict_worker_1, backend_train_worker_1
master_1          | Starting master...
mongo      | WARNING: no logs are available with the 'none' log driver
predict_worker_1  | Starting predict_worker...
rabbitmq   | WARNING: no logs are available with the 'none' log driver
pyspy_1           | py-spy 0.3.3
pyspy_1           | Sampling profiler for Python programs 
pyspy_1           | 
pyspy_1           | USAGE:
pyspy_1           |     py-spy <SUBCOMMAND>
pyspy_1           | 
pyspy_1           | OPTIONS:
pyspy_1           |     -h, --help       Prints help information
pyspy_1           |     -V, --version    Prints version information
pyspy_1           | 
pyspy_1           | SUBCOMMANDS:
pyspy_1           |     record    Records stack trace information to a flamegraph, speedscope or raw file
pyspy_1           |     top       Displays a top like view of functions consuming CPU
pyspy_1           |     dump      Dumps stack traces for a target program to stdout
pyspy_1           |     help      Prints this message or the help of the given subcommand(s)
redis      | WARNING: no logs are available with the 'none' log driver
train_worker_1    | Starting train_worker...
backend_pyspy_1 exited with code 1
master_1          | [2020-06-24 06:09:35 +0000] [1] [DEBUG] Current configuration:
master_1          |   config: None
master_1          |   bind: ['0.0.0.0:8041']
...
```
However, this did not cause the entire docker-compose to break (other containers were still brought up successfully),  and I didn't have any trouble using Pyspy for profiling the remaining containers. I was still able to profile other containers by using `docker-compose run pyspy top --subprocesses --pid *****`. 

**I'm just wondering if this (exited with code 1) is an issue, or Pyspy is just supposed to work like this?**

Below are how I composed Pyspy.

docker-compose.yaml : 
```
services:
    other_containers: 
        ...

    pyspy:
        build:
            context: docker_files/pyspy
        pid: "host"
        privileged: "true"
        volumes:
            - .:/profiles
```

root_dir/docker_files/pyspy :
```
# pyspy/Dockerfile
FROM python:3.7.5
RUN pip install py-spy
WORKDIR /profiles
ENTRYPOINT [ "py-spy" ]
CMD []
```

Much thanks!

**Comment by benfred** [comment]
Looks to me like you're running py-spy with no arguments - and it's displaying it's help message and exiting with an error code of 1 since it requires a python program to profile and a command (dump/top/record etc). This is what should be happening - 

I think you should probably remove 'py-spy' as the entrypoint in your docker file.

**Comment by johnmzz** [comment]
> Looks to me like you're running py-spy with no arguments - and it's displaying it's help message and exiting with an error code of 1 since it requires a python program to profile and a command (dump/top/record etc). This is what should be happening -
> 
> I think you should probably remove 'py-spy' as the  entrypoint in your docker file.

Thank you very much, that makes sense. However, after I removed 'py-spy' as the ENTRYPOINT in the docker file, the system fails to create the container for py-spy. Seems like I still need a specific command in order for it to be brought up.

**Would you suggest a general command that can help me bring up the container? I cannot use `py-spy dump/top/record PID` because I can obtain the PIDs only after the containers are created.**

Using just 'py-spy' as the command, as I did before,  does allow me to create all containers and run Pyspy later on, but it just displays the previous mentioned log messages which I would prefer to get rid of. 

Here's the log I got with no ENTRYPOINT:

```
(base) user $ docker-compose up
Creating network "backend_default" with the default driver
Creating redis ... 
Creatingbackend_pyspy_1 ... error
Creating redis                ... done
Creating mongo                ... 
Creating rabbitmq             ... done
Creating mongo                ... done
Creating backend_train_worker_1   ... done
Creating backend_predict_worker_1 ... done
Creating backend_master_1         ... done

ERROR: for pyspy  Cannot create container for service pyspy: No command specified
ERROR: Encountered errors while bringing up the project.
```

And here's my modified dockerfile, only removed entrypoint:

```
# pyspy/Dockerfile
FROM python:3.7.5
RUN pip install py-spy
WORKDIR /profiles
CMD []
```

Docker-compose.yml remains unchanged.

Much thanks!
