### ISSUE TITLE
Run py-spy in Github actions to profile process in Docker

### ISSUE THREAD

**Issue by whatnick** [benfred/py-spy#276]
Attempting to run py-spy via GitHub actions to get performance profiles on our Flask App. However the SIGINT 2 to kill py-spy is making it a bit hard to run in CI. Would be nice to have a run with timeout mode built into py-spy for fixed time length sampling. 

See the last attempt at a CI run [here](https://github.com/opendatacube/datacube-ows/pull/350/checks?check_run_id=902904345) for datacube-ows. Previous manually run profile [here](https://gist.githubusercontent.com/whatnick/ad0cb63eda2fe67e51f4ec43450179b1/raw/54a5668a632e433ba703678ee996f6d85d301812/profile.svg)

**Comment by benfred** [comment]
There is a `duration` flag that tells py-spy how long to sample for. Running ```py-spy record -o profile.svg --duration 30 -p 12345``` will sample for 30 seconds before writing out the profile. Have you tried using this?

**Comment by whatnick** [comment]
Nope I solved it the hard way using SIGINT with timeout CLI tool. `timeout -s 2 30 py-spy -- flask` . Should have read the docs more.
