### ISSUE TITLE
[Question] building py-spy for ppc64le processor architecture

### ISSUE THREAD

**Issue by AlessandroZavoli** [benfred/py-spy#277]
the command `pip install py-spy` does not seam to work on IBM power pc.
Is it possible to build py-spy for ppc64le processor architecture?

Alessandro

**Comment by benfred** [comment]
I haven't tried building py-spy on ppc64le before - but it very well might work if you want to give it a go. We handle ARM processors, and there was very little that needed to change to support that (aside from disabling some x86_64 specific code for profiling extensions - see https://github.com/benfred/py-spy/issues/89), and I don't see why this wouldn't work with ppc64le

You'll need to download and install rust and cargo to build - after which you can try ```cargo install py-spy``` which should try to build everything for you. The version on pypi just has precompiled binary wheels, and afaik pip doesn't support ppc64le binary wheels yet.

**Comment by AlessandroZavoli** [comment]
may i install rust and cargo without "sudo" or administrator privilegies?

**Comment by benfred** [comment]
yeah - by default it only installs for your user profile (into ~/.cargo/bin). Following these steps should work https://www.rust-lang.org/tools/install

**Comment by rkube** [comment]
Hi,
I've managed to install rust and py-spy this way:
1. Install rust as described here: https://www.rust-lang.org/tools/install
2. Add cargo to my PATH: export PATH=$PATH/.cargo/bin
2. cargo install py-spy

**Comment by benfred** [comment]
nice! Thanks @rkube for verifying this works - closing
