### ISSUE TITLE
--verbose to not truncate locals?

### ISSUE THREAD

**Issue by mattp-** [benfred/py-spy#287]
I can understand truncating by default for usability, but sometimes huge objects are sometimes needed to be poked into. is there a way to provide this via a verbosity flag similar to pytest's locals functionality?

**Comment by benfred** [comment]
This change https://github.com/benfred/py-spy/pull/288 should let you view more info from local variables: like ```py-spy dump -llll -p PID```   won't truncate until the local variable is 512 chars long (vs the default 128).

**Comment by benfred** [comment]
Change is in v0.3.4
