### ISSUE TITLE
Include command/options used to run py-spy in flamegraph output

### ISSUE THREAD

**Issue by clokep** [benfred/py-spy#293]
I'll frequently run py-spy a few times in a row with slightly different parameters (e.g. with and without `--gil`, with and without `--threads`) and then look at them all after the fact. It can be a bit confusing to remember flamegraph is from which run.

It would be convenient if the command used to run py-spy (or the options) was recorded somewhere into the output file. Maybe as the title at the top of the svg?

**Comment by benfred** [comment]
I think this is a great idea - I'm switching the 'py-spy' in the flamegraph svg to be the full commandline in https://github.com/benfred/py-spy/pull/359

**Comment by clokep** [comment]
Thanks so much!
