### ISSUE TITLE
MPI support/workaround?

### ISSUE THREAD

**Issue by Chronum94** [benfred/py-spy#298]
Are there any plans to support/a preferred workaround for MPI?

A fair number of runs of mine go as `mpirun -np 4 python scriptname.py`. Is there any methodology/workaround for being able to py-spy on all these processes together?

Currently, my go-to is 'okay here are the 4 processes I want to look at, let me make a bash script that goes over all of those processes and starts recording them'.

**Comment by benfred** [comment]
Have you tried the subprocess support built in to py-spy? if you give  the subprocesses argument to py-spy it should profile all the child processes

**Comment by Chronum94** [comment]
Would that works as so?

`mpirun -np 6 py-spy record --output mpitestoptimizer.scope --format speedscope python optimize.py --subprocesses -r 25`

It appears to be doing what I'd like it to, but the output appeared to be in one stream (this may be a speedscope issue).

1. Is the above syntax doing what I'd like it to do? I'm hopeful, since there are 6 'recording' statements.
2. Is there any way to have process-resolved timings?

Really appreciate the great package and the quick responses.

**Comment by benfred** [comment]
Can you try

``` py-spy record --output mpitestoptimizer.scope --format speedscope --subprocesses  --r 25 -- mpirun -np 6 python optimize.py ``` instead?

We want to get py-spy to profile the mpirun process and all of its subprocesses . It seems to me that with the command line you gave,  it might be spawning 6 different py-spy processes instead with each py-spy process only recording a single worker process. 

Btw, I'm assuming that this is all happening on a single machine - let me know if I'm wrong on that assumption.

The process hierarchy should be shown in the output with the subprocesses option

**Comment by Chronum94** [comment]
`Error: No python processes found in process 2722 or any of its subprocesses`

I think a key problem here is that all MPI processes are in a sense equivalent, and I'm not sure if there are 'subprocesses' being spawned. I may be completely and utterly off though...

**Comment by Chronum94** [comment]
@benfred I can close this issue if there's no clear way to get this, or I can leave it open if you think support for this may be added eventually.
