### ISSUE TITLE
How are race conditions avoided

### ISSUE THREAD

**Issue by P403n1x87** [benfred/py-spy#32]
I still have no knowledge of Rust so I might have missed something, so apologies for that if this turns out to be a silly question. As far as I understand the code relative to Linux, the target process memory is read on-demand rather than in just one call to process_vm_readv. Since the target process is not stopped, how are race conditions avoided when unwinding the interpreter state? Can it not happen that, while the profiler is navigating the list of frames, this is suddenly invalidated by, e.g., the associated thread dying?

**Comment by benfred** [comment]
I'm going to add some info to the readme, but I wrote a bit about this already here https://github.com/benfred/py-spy/issues/26
