### ISSUE TITLE
Duration seems to depend on the number of processes, not seconds. Or on threads...

### ISSUE THREAD

**Issue by mborus** [benfred/py-spy#33]
I'm testing the flamegraph for a minute on PID 502 calling

py-spy -p 502 -d 60 -f /tmp/flame

on a Linux CentOS 5 machine,

I get a progress bar that only moves slowly. 
I'm using the default sample rate of 1000. 

It seems that duration seconds doesn't consider cases where 
there's less samples than the maximum defined. Or see 2nd
theory below...

Output:
Sampling process 1000 times a second for 60 seconds
████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 60000/60000
Wrote flame graph '/tmp/flame'. Samples: 60000 Errors: 0

Also in this scenario, the flamegraph might be wrong/confusing,
The generated svg file has a first line
Function all: (255,466 samples 100%)

Which is inconsistent with the collected 60000 samples.

The next line shows "<module> /main.py:25)" at 59999 samples
and the rest at "_bootstrap" (threading.py:884) 195,457 samples,
so it's possible that the default 1000 samples a second are taken,
but those from threads don't count towards the duration.

The job ran about 4 minutes, so that would work out.

**Comment by benfred** [comment]
Weird. Setting the duration flag seems to work appropiately for me:
```discord:py-spy ben$ time sudo target/release/py-spy -d 10 --flame d.svg python tediscord:py-spy ben$ time sudo target/release/py-spy -d 10 --flame d.svg python test_programs/looper.py 
Sampling process 1000 times a second for 10 seconds
█████████████████████████████████████████████████████████████████████ 10000/10000
Wrote flame graph 'd.svg'. Samples: 10000 Errors: 0

real	0m10.170s
user	0m1.172s
sys	0m1.729s
```

I'm wondering if what's happening here is that we're sampling slower than 1K times a second for some reason, and it isn't keeping up. I'm going to add some code to detect if this happens and write out an error message in this case.

Can you try again with setting a lower rate just to verify? Maybe ```--rate 100``` or something like that?

**Comment by benfred** [comment]
The 0.1.6 release has code to warn if we aren't sampling fast enough - which I think was the issue here

**Comment by mborus** [comment]
I made an update and now get the warning on the sample rate 1000 like this
24.68s behind in sampling, results may be inaccurate. Try reducing the sampling rate.
and no warning on the sample rate 100 (speed is OK, too)

**Comment by benfred** [comment]
thanks for letting me know! It's weird that the max sampling rate is so low for your system (I have no problem on most machines up to 10K samples a second), but I'm glad the problem is sorted out.
