### ISSUE TITLE
Output raw call stack data

### ISSUE THREAD

**Issue by nziebart** [benfred/py-spy#35]
It would be useful (and I suspect not too difficult) to be able to retrieve the raw call stack data for an invocation of py-spy. This would allow aggregating data from many machines, and performing ad-hoc aggregations over different time ranges.

**Comment by benfred** [comment]
This shouldn't be too hard to do. 

I'm also thinking about adding a python api (using approach I wrote about here: http://benfrederickson.com/writing-python-extensions-in-rust-using-pyo3/) which would let you script operations like this.

**Comment by nziebart** [comment]
A python api would be awesome!

**Comment by nziebart** [comment]
It would also be nice to be able to get "idle" stack traces (i.e., not omit them). Sometimes it's useful to know where idle time is being spent (e.g., I might want to know what % of time I spend waiting on a particular db query)

**Comment by Norbo11** [comment]
Any progress on this?

I have a totally different use case than simply generating flame graphs or viewing the profiling information in real-time. I would love to be able to get the raw data used to generate the flame graph, for example.

**Comment by benfred** [comment]
I've added this in v0.2.0

@nziebart there is also now a ``--idle``` flag to show idle frames
