### ISSUE TITLE
Invalid PID numbers are poorly reported

### ISSUE THREAD

**Issue by fake-name** [benfred/py-spy#36]
Basically:

```
durr@rwpscrape ~> sudo py-spy --pid 12345
Error: No such file or directory (os error 2)
```

It turns out that I initially ran into this problem when the PID I was trying to sniff went away before I had switched to actually executing `py-spy`. It turns out that if you pass a PID that isn't in use, you get `Error: No such file or directory (os error 2)`. 

It'd maybe be nice to have that case return something like "Error: No such file or directory (os error 2). Is that PID Valid?" or similar. as it is, I wound up flailing about a bit before I figured out the actual issue.

**Comment by benfred** [comment]
Agreed - we should handle this better. It should be pretty easy to detect if the PID isn't running and output an informative error message in this case.

**Comment by fake-name** [comment]
Yeah, it's not critical, but it would be a nice-to-have thing.

**Comment by fake-name** [comment]
Cool!
