### ISSUE TITLE
speedscope js error (just chrome)

### ISSUE THREAD

**Issue by TZanke** [benfred/py-spy#369]
I got a error after uploading my file:

![image](https://user-images.githubusercontent.com/1613368/113871036-c4672900-97b2-11eb-8465-babe68a355c6.png)

Just happens in Chrome Version 89.0.4389.72 (Offizieller Build) (64-Bit)
Firefox works fine 78.8.0esr (64-Bit)

**Comment by Asday** [comment]
Sounds like a speedscope issue, not a py-spy one.

**Comment by TZanke** [comment]
@Asday thank you.

https://github.com/jlfwong/speedscope/issues/358
