### ISSUE TITLE
Windows 7: ANSI code to clear the rest of the line gives additional characters: `←[K`

### ISSUE THREAD

**Issue by kud1ing** [benfred/py-spy#37]
On a German Windows `cmd` the output looks like this:

```
Collecting samples from 'pid: 17092' (python vX.Y.Z)←[K
Total Samples 598500←[K
GIL: 0.00%, Active: 200.00%, Threads: 2←[K
←[K
  %Own   %Total  OwnTime  TotalTime  Function (filename:line)
 99.40%  99.40%   572.4s    572.4s   run (foo.py:733)←[K[K
 84.10%  84.10%   109.4s    109.4s   foo (foo:4698)←[K
 11.50%  11.50%   13.13s    13.13s   foo (foo:4681)←[KK
  1.80%   1.80%    2.09s     2.09s   foo (foo:4676)←[KK
  0.90%   0.90%   0.791s    0.791s   foo (foo:4693)←[KK
  0.60%   0.60%   26.03s    26.03s   run (foo.py:728)←[K)←[KK
  0.40%   0.40%   0.555s    0.555s   foo (foo:4700)←[KK
  0.30%   0.30%   0.558s    0.558s   foo (foo:4694)←[KK2031)←[K
  0.30%   0.30%   0.508s    0.508s   foo (foo:4701)←[KK2031)←[K
  0.30%   0.30%   0.276s    0.276s   foo (foo:4695)←[KK2031)←[K
  0.20%   0.20%   0.043s    0.043s   foo (foo:4674)←[KK2031)←[K
  0.10%   0.10%   0.102s    0.102s   foo (foo:4691)←[K[K031)←[K
  0.10%   0.10%   0.035s    0.035s   foo (foo:4699)←[K[K031)←[K4)←[K
←[K
Press Control-C to quit, or ? for help.←[K
←[K
←[K
```

They seem to come from the macro `out!`:
https://github.com/benfred/py-spy/blob/c2813e57a5807a3718233914eea13c31b80a3a1b/src/console_viewer.rs#L128

**Comment by benfred** [comment]
What version of windows are you running? Also, is in the in cmd.exe or powershell? 

I tested on windows 10 (english) and using ANSI codes like this worked for me =(

**Comment by kud1ing** [comment]
Windows 7

**Comment by benfred** [comment]
Thanks for reporting this! I'll see if I can get a windows 7 box to replicate this on somehow.

**Comment by kud1ing** [comment]
Thanks.

**Comment by kud1ing** [comment]
I don't know much about Windows, but it seems that ANSI escape sequences were not supported before Win 10: https://stackoverflow.com/questions/16755142/how-to-make-win32-console-recognize-ansi-vt100-escape-sequences

**Comment by kud1ing** [comment]
I wonder whether there is a crate that does something like this correctly across platforms and operating system versions.

**Comment by benfred** [comment]
I managed to reproduce this in a vagrant/virtualbox environment. This commit b32c4942e8db22883096f85e489039a41096d5b0 seems to fix, will be in the next release. 

thanks for reporting this!

**Comment by kud1ing** [comment]
Awesome, thank you.

**Comment by kud1ing** [comment]
Do you have a plan when to releases this? It's my final thorn.

**Comment by benfred** [comment]
@kud1ing I just pushed 0.1.7 which should include this (windows wheels are generating on appveyor, should be pushed out in ~10 mins)

**Comment by kud1ing** [comment]
Nice, thank you.

**Comment by kud1ing** [comment]
Works perfectly, thanks.
