### ISSUE TITLE
Flame graphs without Perl

### ISSUE THREAD

**Issue by kud1ing** [benfred/py-spy#38]
Options to create flame graphs in Rust:

* @TyOverby's https://github.com/TyOverby/flame produces HTML/D3.js flame graphs in Rust.
  * https://github.com/TyOverby/fireplace
* @jonhoo's https://github.com/jonhoo/inferno

Other options:

* https://github.com/jlfwong/speedscope
  * https://github.com/jlfwong/speedscope/wiki/Importing-from-custom-sources#speedscopes-file-format

See also https://github.com/benfred/py-spy/issues/7

**Comment by TyOverby** [comment]
@kud1ing I've actually been working on a new project for flamegraph visualization here
https://github.com/TyOverby/fireplace

Example of a simple flame graph being visualized: 
<img width="336" alt="image" src="https://user-images.githubusercontent.com/573215/45602283-8d508280-b9d0-11e8-8431-1c3a0d357a96.png">

After working on it for quite some time, I found https://www.speedscope.app/ and it's better in almost every way.  I'm going to work on getting bincode to export to something that speedscope can read.

**Comment by Yajo** [comment]
I also love speedscope. This issue should be relabeled "support speedscope format" or similar.

**Comment by aparamon** [comment]
It seems that https://www.speedscope.app supports performance logs as output by e.g. https://github.com/evanhempel/python-flamegraph and compatible with https://github.com/brendangregg/FlameGraph.

Adding option to dump raw performance logs will provide a https://github.com/benfred/py-spy/issues/45 and it a very low-hanging fruit.

**Comment by kud1ing** [comment]
There is also now https://github.com/jonhoo/inferno

**Comment by jlfwong** [comment]
Hi! speedscope author here. FWIW, while the stack collapse format output accepted by `brendangregg/FlameGraph` does indeed import successfully into speedscope, you'll get a higher quality import complete with filenames and line numbers if you target speedscope's own file format.

More information here: https://github.com/jlfwong/speedscope/wiki/Importing-from-custom-sources#speedscopes-file-format

I contributed support to rbspy to output to this format: https://github.com/rbspy/rbspy/pull/161

Once some way of importing into speedscope from py-spy exists, regardless of what it is, please let me know and I'll update speedscope's own documentation to list it as supported 😄

**Comment by pquentin** [comment]
I would also be happy to be able to use py-spy without having to first install perl in my Docker containers.

**Comment by benfred** [comment]
That latest PR removes the need for perl: https://github.com/benfred/py-spy/pull/114. 

I also totally agree that getting speedscope support in here is worth doing. I've created a new issue to track https://github.com/benfred/py-spy/issues/115 - thumb it up if you think I should prioritize

**Comment by benfred** [comment]
fix is in v0.1.11
