### ISSUE TITLE
`py-spy -- cmd` doesn't work

### ISSUE THREAD

**Issue by stas00** [benfred/py-spy#395]
Trying to use `py-spy` on a system w/o `sudo` - the docs suggests something that doesn't work:
```
py-spy -- python -c "1"
error: The subcommand 'python' wasn't recognized
```

This is just a silly test to reproduce the problem.

```
py-spy --version
py-spy 0.3.6
```

Thank you.

**Comment by benfred** [comment]
thanks! fixed the README to have correct instructions in that sudo section

**Comment by stas00** [comment]
Thank you, @benfred 

I'm not sure though how this can help with getting a dump when a program is hanging. For some reason I thought that there was a way to do it like it performs w/ `sudo`

Should there be a custom sighandler registered or perhaps a key registered inside the `top` sub-command and when pressed it'd dump the current tbs?

**Comment by benfred** [comment]
The best way to get a dump when a program is hanging is probably to use the dump command against the pid of the process ```sudo py-spy dump -p PID``` .  Is the issue here that you don't have sudo or root access?

If you don't have root access and want to figure out where your program is hanging its a little more complicated. One option is to record a profile using the speedscope format until it's hung, and then use the 'time order' view in speedscope to look at the stack at the point where the process is hanging.

**Comment by stas00** [comment]
> The best way to get a dump when a program is hanging is probably to use the dump command against the pid of the process `sudo py-spy dump -p PID` . Is the issue here that you don't have sudo or root access?

Yes. 

It works great w/ `sudo`, but I'm now on a system where I don't have it.

> If you don't have root access and want to figure out where your program is hanging its a little more complicated. One option is to record a profile using the speedscope format until it's hung, and then use the 'time order' view in speedscope to look at the stack at the point where the process is hanging.

It sounds doable, but it could be very slow if it's going to record everything.

Won't using a sighandler or pressed key handler be much simpler for the user? Basically emulate `sudo py-spy dump` but w/o needing `sudo`?

Not sure though whether `sighandler` is a good approach. Most of the time if I try to use `faulthandler` sighandler doesn't work:
```
import faulthandler, signal
faulthandler.register(signal.SIGUSR1)
# kill the stuck process
kill -USR1 PID
```

I think it's because various applications "steal" this handler. I forget if I tried other signals.

Therefore I have to use its scheduled dumping instead.

```
import faulthandler
faulthandler.dump_traceback_later(20, repeat=True)
```

feature, but the problem is that very often it generates garbled, unreadable dumps.

So that's why I think registering a non-sighandler key polling process under a new sub-command like `watch-n-dump` might be a more workable solution.

So far `py-spy` has been the best program hanging diagnosis tool, but as I mentioned I can't use it on a system w/o sudo.

**Comment by benfred** [comment]
> It sounds doable, but it could be very slow for a massive program if it's going to record everything.

You could always set the sampling rate low - (like one sample a second etc), but yeah this could start to eat up memory if you're going to be running it over the course of many hours

> Won't using a sighandler or pressed key handler be much simpler for the user and also much faster? Basically emulate sudo py-spy dump but w/o needing sudo?

If we were going to go this route, I'd probably go with the a key handler over a sighandler. Maybe even just go with what you suggested and have an option in the 'top' command to dump the current stack.

**Comment by stas00** [comment]
> If we were going to go this route, I'd probably go with the a key handler over a sighandler. 

I'm with you on the key handler.

> Maybe even just go with what you suggested and have an option in the 'top' command to dump the current stack.

the normal `top` won't work for programs with massive std* output - e.g. machine learning training programs, so it'd be a big mess if the program will try to refresh the screen and dump a ton of unrelated output the whole time.

Unless we can set `top` to refresh once in an 10 min, and then it'd be OK. This is for debug, so occasional use and doesn't have to be perfect.

**Comment by stas00** [comment]
@benfred, would it help to create a dedicated issue - as the original issue has been closed?

**Comment by benfred** [comment]
> @benfred, would it help to create a dedicated issue - as the original issue has been closed?

That would be great!

**Comment by stas00** [comment]
continued here: https://github.com/benfred/py-spy/issues/408
