### ISSUE TITLE
profile with python module

### ISSUE THREAD

**Issue by ThyrixYang** [benfred/py-spy#404]
Hi, 

I'm attempted to run a python module using
`py-spy record -o /tmp/profile.svg python -m package.script`
However, it said that 
`error: Found argument '-m' which wasn't expected, or isn't valid in this context`
How can I do this correctly?

**Comment by benfred** [comment]
Try putting a -- between the py-spy command and the python command:

py-spy record -- python -m package.script

**Comment by ThyrixYang** [comment]
Thanks!
