### ISSUE TITLE
Doubt on recording python subprocesses of different versions

### ISSUE THREAD

**Issue by Roberto09** [benfred/py-spy#413]
Hi! I really like your software and been using it a lot recently; however I had a small doubt about a use case: say we have 2 python scripts A and B using 2 different python versions (say A uses 3.X and B uses 2.X). I first launch A, then I start recording process A with 'py-spy record' using the '-s' option, after that I launch the subprocess B from the process A using the subprocess lib.

I've been reading some parts of your code and, as I understand, py-spy requires to know the python version from the process it's recording. I've already tried this with some simple example code I made and py-spy seems to be recording properly what happens in process B. However my concern is that, in case B has more complex stuff, would py-spy still be able to record everything on B? My concern arises from the fact that py-spy needs to know the python version of whatever it's recording (in this case the process A) but B, in this case, has a different one.

Are there any caveats or special considerations to make here?

Thanks!

**Comment by benfred** [comment]
The case you described should work (like you can profile sub processes that are different versions of python). Py-spy handles multiple versions of python, and each subprocess is handled independently

Have you seen any issues when doing this?

**Comment by Roberto09** [comment]
> The case you described should work (like you can profile sub processes that are different versions of python). Py-spy handles multiple versions of python, and each subprocess is handled independently
> 
> Have you seen any issues when doing this?

Oh sounds good!
I haven't seen issues with this on the example tests I've run, nonetheless I'll start trying this out more and let you know if anything interesting comes up. Thanks!!
