### ISSUE TITLE
No Apple Silicon wheel available

### ISSUE THREAD

**Issue by kpitzen** [benfred/py-spy#419]
It would be ideal if wheels could be provided for machines running apple silicon processors.  I'm able to build with cargo, but projects like python `ray` provide py-spy as a dependency, which requires them to be pip-installable on the local architecture.

**Comment by ZetiMente** [comment]
Hi, I am having this same issues. 

I will send you $25 USD in BTC if you could take the time to release a wheel for Apple Silicon.

**Comment by ZetiMente** [comment]
Oh, and check out this project. 

https://github.com/PyO3/maturin

I don't know if your situation is more unique, but it makes building Python wheels incredibly easy. It replaces setuptools with less configuration.

**Comment by benfred** [comment]
Thanks to @messense  - Apple silicon wheels are now being built as of #420. You can download built wheels from the 'artifacts' bundle here - https://github.com/benfred/py-spy/actions/runs/1032421855  , and they will be included in the next version (which I will push out in a couple of days probably).

**Comment by theword** [comment]
Yay!!! Looking forward to the release!!! 

@messense If you send me your BTC wallet address, I will send you some BTC for your hardwork! Thank you so much!!!

**Comment by ZetiMente** [comment]
Yay!!! Looking forward to the release!!!

@messense If you send me your BTC wallet address, I will send you some BTC for your hardwork! Thank you so much!!!

**Comment by messense** [comment]
@ZetiMente Thanks for the offer, but I'm not doing this for money. Glad to help.

**Comment by ZetiMente** [comment]
@benfred Please, can I beg you to release the next version to pypi ?

**Comment by benfred** [comment]
@ZetiMente v0.3.8 will be uploaded to pypi by CI in about 20 minutes https://github.com/benfred/py-spy/actions/runs/1084528446

**Comment by ZetiMente** [comment]
> @ZetiMente v0.3.8 will be uploaded to pypi by CI in about 20 minutes https://github.com/benfred/py-spy/actions/runs/1084528446

Thank you so much! Hope you have a wonderful day!
