### ISSUE TITLE
Support pyinstaller binaries

### ISSUE THREAD

**Issue by DavidVentura** [benfred/py-spy#42]
At the moment if you try to run py-spy on a binary created by py-installer you get 

```
Error: Failed to find python version from target process
```

A trivial fix would be to allow the user to specify the version in case it cannot be detected.
Not entirely sure if the rest would work..

**Comment by benfred** [comment]
What operating system are you on? I managed to replicate this on OSX, but want to make sure I'm targeting the right platform. Also can you enable logging and paste the output here (```export RUST_LOG=info``` on osx/linux or ```set RUST_LOG=info``` on windows cmd.exe then run the command again).

I don't think the rest would work even if we passed the version in - py-spy is failing to find the right libpython binary, so even with the right version it would fail to find the python interpreter.

On OSX pyinstaller is bundling the libpython to something like

```
 INFO 2018-09-21T19:26:51Z: py_spy::python_spy: map: 0000000100c1c000-0000000100d11000 r-x /Users/ben/code/py-spy/test_programs/dist/test/Python
```

and we are expecting something like 'libpython' or 'Python.Framework/.../Python'. I'm not sure what this is like on other systems =(.

**Comment by DavidVentura** [comment]
I'm on debian/centos. Would you mind making a release that allows you to specify the version and the offset for the `PyInterpreterState` (or something that is useful)? then I could play with this trying to figure out how to get this address out of the static binary in a nice way

**Comment by benfred** [comment]
This commit should fix the failing to find libpython problem with pyinstaller: https://github.com/benfred/py-spy/commit/064b8e72825445d506401e1a663b3b4df94279fb

This will be in the next release. Note that you still will need to pass the pid of the python subprocess for now.

**Comment by benfred** [comment]
fixed in v0.1.8

**Comment by DavidVentura** [comment]
Working great! Thank you

**Comment by benfred** [comment]
hmm - marking these as idle seems unideal too though (would show process not being busy, when it's busy in subprocessess). I'm going to add an issue for a config file where you can specify custom functions to exclude.

Also I think eventually it would be good to also sample from subprocesses

**Comment by DavidVentura** [comment]
In this case, looking at real cpu usage only 1 process is busy. The subprocesses only send a message via a queue at the very end of the processing, so there's also no communication.
