### ISSUE TITLE
No setup.py file in version 0.3.8

### ISSUE THREAD

**Issue by simon28li** [benfred/py-spy#432]
May I ask why there is no setup.py file in version 0.3.8?

**Comment by benfred** [comment]
We switched the build system over to use maturin (to get apple silicon support). The build config is in pyproject.toml instead of setup.py now. You can still install py-spy using pip with 'pip install -e .' 

Is this causing any issues for you?

**Comment by simon28li** [comment]
We built it using the tool spack (https://github.com/spack/spack), which is installed using the command `python setup.py build`. There is no such file now, which causes the installation of the latest version to fail.

**Comment by messense** [comment]
Looks like spack don't have PEP 517 support for Python yet: https://github.com/spack/spack/issues/6629#issuecomment-607727712

**Comment by messense** [comment]
I'd recommend change the spack py-spy package spec to just build with Cargo instead, it doesn't  need to be built with PythonPackage.

**Comment by benfred** [comment]
@messense upgraded the spack package to build with Cargo instead (thanks!) . Closing this issue
