### ISSUE TITLE
Change flame-graph default duration when starting a process

### ISSUE THREAD

**Issue by 3tilley** [benfred/py-spy#44]
This is kind of related to https://github.com/benfred/py-spy/issues/21, but not exactly the same.

It would also be helpful if when launching py-spy to start a Python process, the default behaviour would be to run the flame-graph until the process terminated. Currently I am running:
    py-spy --flame profile.svg --duration=10000 -- python myprogram.py

Allowing a duration option of -1 for this behaviour would also fix the issue. I've never written Rust, but I could probably figure out how to do this myself, but not to support the referenced issue above.

**Comment by CoenraadS** [comment]
I also expected this behavior by default. Now I run `--rate 1 --duration 999999999`

**Comment by aparamon** [comment]
@MuchkoM Could you please try make a PR?

When a process is started by `py-spy` (as opposed to attaching), the default `duration` should be the lifetime of the process. `py-spy` should stop once the process is finished (this is not specific to starting a process though, generally).

**Comment by benfred** [comment]
Thanks everyone! The default duration is now the lifetime of the process in v0.2.0
