### ISSUE TITLE
Most recent release uses yanked crates

### ISSUE THREAD

**Issue by cinerea0** [benfred/py-spy#461]
Currently, the most recent release of py-spy (v.0.3.10) relies on a yanked version of `rand-core`. This makes it difficult to provide updates for py-spy for some Linux distros. Could you please cut a new release with updated dependencies?

**Comment by benfred** [comment]
v0.3.11 is being pushed out now (https://github.com/benfred/py-spy/actions/runs/1455328479) with updated dependencies - it will be available on pypi/crates.io/github releases in 30 minutes or so
