### ISSUE TITLE
Show thread names in --dump

### ISSUE THREAD

**Issue by mgedmin** [benfred/py-spy#47]
Python threads have names:

```
>>> import threading
>>> threading.current_thread().name
'MainThread'
```

It would be very nice if py-spy --dump could print those names.

**Comment by benfred** [comment]
I agree that this would be nice - but unfortunately getting this would be slightly involved, and I doubt I'll get to it anytime soon =(.

 From what I can tell, the names live on the Thread object in threading.py.  To read these from another process we'd have to implement the equivalent code in rust:

```python
for threadid, thread in sys.modules['threading']._active.items():
    print(threadid, thread._name))
```
while it doesn't look all that bad, it does mean we'd have to add logic to read python dict objects from another process in rust (for getting the threading module, getting the _active variable from the modules globals dict, getting the items from the _active  and finally getting the _name member from the Thread class `__dict__`). 

It's not hard exactly, but would be a little time consuming to implement =(

**Comment by benfred** [comment]
First draft of this is in #176. I added the ability to show the local variables in that PR, and once that was done getting the thread names was pretty easy.

Note this is limited to python 3.6+ right now - older versions of python will still just show the threadid without the namee.

**Comment by benfred** [comment]
change is in v0.2.2 release
