### ISSUE TITLE
How to record with python_program

### ISSUE THREAD

**Issue by caimaoy** [benfred/py-spy#475]
It can record with 
```shell
py-spy record [OPTIONS] --output <filename> --pid <pid> [python_program] <arg1> <arg2> ...
```
but if `arg1` and `arg2` have the args like `-g` or `--pid` and in another situation `python_program` use `vitrulenv` or `pyenv`
how to solve the problems？I can only record with `--pid ` without `[python_program] <arg1> <arg2> `

**Comment by benfred** [comment]
@Jongy is exactly right - you just separate the python program commandline with a `--`
