### ISSUE TITLE
Combine multiple runs into one file

### ISSUE THREAD

**Issue by tsafs** [benfred/py-spy#476]
Say I have multiple docker containers which run the same software in parallel. On each container I start an instance of py-spy monitoring that software. Is there a way to combine the results into one file, such that in `speedscope` the `left heavy` view would group the same call stacks of the various processes together?

**Comment by Jongy** [comment]
You can use `--format raw` to get raw stackcollapsed format. Merging them done by simply concatenating the files. Then, you can convert the result back to speedscope.

**Comment by olejorgenb** [comment]
How do you convert the raw format back to speedscope format?
