### ISSUE TITLE
"Killed: 9"?

### ISSUE THREAD

**Issue by spencerwilson-optimizely** [benfred/py-spy#48]
Hello there,

Thank you for your work on the tool! I'm very excited to use it, but seem to have hit a snag:
```sh
17:12 ~/code/optimizely/src/www
$ pstree 98465
--- 98465 swilson /Users/swilson/code/optimizely/.virtualenv/www/test/bin/python /Users/swilson/code/optimizely/.virtualenv/www/test/bin/pytest --pdb services_test/client_tes [truncated]

17:13 ~/code/optimizely/src/www
$ sudo py-spy --pid 98465 -f hottt
Killed: 9
```
I've ensured that the PID of `pytest` isn't moving around; i.e., it's a long-running process with no child processes. Yet _while it's running_, I get the output `Killed: 9`, exit status 137.

Python 2.7.12
py-spy 0.1.8
macOS 12.13.6

Let me know if I can provide any other details!

**Comment by benfred** [comment]
So - it sort of looks like something killed py-spy =(by going 'kill -9' or similar) =(.

Can you figure out what process issued the SIGKILL?  There are probably a bunch of ways of getting this, but an easy first stab might be to use dtrace.  Running these commands:

```bash
curl  http://www.brendangregg.com/DTrace/kill.d > kill.d
sudo /usr/sbin/dtrace -qs kill.d 
```

will print out a series of lines with the sending process info and what signal is being sent every time a signal happens on your machine. If you filter down to '9' signals sent at the same time py-spy is killed, you should get the process that is killing it.

**Comment by spencerwilson-optimizely** [comment]
For reference, here's the line of code that's coming from:
https://github.com/millert/sudo/blob/SUDO_1_8_17p1/src/exec.c#L223-L224

**Comment by spencerwilson-optimizely** [comment]
More data, demoing the 'direct invocation' style + showing I'm not trying to use /usr/bin/python:
```
09/:05 ~/code/optimizely-integrations
$ cat foo.py
while True:
  1 + 1

09:05 ~/code/optimizely-integrations
$ sudo py-spy -- /Users/swilson/.pyenv/versions/2.7.12/bin/python foo.py
Killed: 9
```

**Comment by spencerwilson-optimizely** [comment]
Ah, looks like the process gets created, but as a child of /sbin/launchd:
```
09:27 ~/code/optimizely-integrations
# via https://askubuntu.com/q/56266
$ logpid() { while sleep 1; do  ps -p $1 -o pcpu= -o pmem= ; done; }

09:27 ~/code/optimizely-integrations
$ sudo py-spy -- /Users/swilson/.pyenv/versions/2.7.12/bin/python foo.py
Killed: 9

09:27 ~/code/optimizely-integrations
$ pstree -p 21178
-+= 00001 root /sbin/launchd
 \--- 21178 root /Users/swilson/.pyenv/versions/2.7.12/bin/python foo.py

09:27 ~/code/optimizely-integrations
$ logpid 21178
 99.0  0.0
100.0  0.0
100.0  0.0
 99.7  0.0
100.0  0.0
100.0  0.0
100.0  0.0
^C
```

**Comment by benfred** [comment]
Hmm, weird.

Instead of launching py-spy like ```sudo py-spy ..``` can you go like ```sudo su``` to get a shell session as root, and then run py-spy from that ? I'm interested to see if sudo still kills itself in this case. 

Can you also enable logging in py-spy? (```RUST_LOG=info py-spy --pid 123456```).

I think the error message from using the system python would be different. (also the system python on high sierra is 2.7.10 instead).

**Comment by spencerwilson-optimizely** [comment]
hm, I have another machine, macOS 10.13.4 w/ SIP enabled, and `sudo py-spy -- $(pyenv which python) foo.py` works fine there.

**Comment by benfred** [comment]
I don't think this problem is related to SIP - iirc the error messages when hitting SIP are a permissions denied error (also it's not getting that far =).

Based off the logs, py-spy is getting killed when reading the virtual memory maps - which really only calls task_for_pid followed by a couple of mach_vm_region calls: https://github.com/rbspy/proc-maps/blob/96b274b826d7f9246856986af632b33672e9a7d9/src/mac_maps/mod.rs#L93-L95

You should be able to see these calls running with something like 
```bash
sudo  dtrace -n 'pid$target::mach_vm_region:entry'  \
                      -n 'pid$target::task_for_pid:entry' \
                       -c 'target/debug/py-spy -f o.svg -- python foo.py'
```

which should list one task_for_pid call followed by a bunch of mach_vm_region (to get the memory maps). if this works there will also be an extra task_for_pid call at the end (to get the handle to read the process memory).

I'm really not sure why this would cause a sigkill though =( Do you have any antivirus software running? Or is there any other major differences in the environment between your machines?

**Comment by benfred** [comment]
hmm - actually you should be able to use dtruss, and if you can't you probably can't use dtrace either 🤦‍♂️ .

Can you use dtruss/dtrace on your python (without py-spy) ? like does ```dtruss python foo.py``` bring up the same error? 

I'll try out re-enabling SIP tomorrow to test out.

**Comment by spencerwilson-optimizely** [comment]
I identified the issue with dtruss:
```
21:55 ~
$ which py-spy
/Users/swilson/.pyenv/shims/py-spy

21:55 ~
$ head -n1 $(which py-spy)
#!/usr/bin/env bash
```
`sudo dtruss py-spy ...` attempts to trace /usr/bin/env, which is a no-go under SIP (just like attempting to py-spy on /usr/bin/python, I suspect). Substituting with `sudo dtruss $(pyenv which py-spy) ...` works! So I think that's a red herring. Sorry for that distraction >_>

The output of the command you suggested above:
```
$ sudo  dtrace -n 'pid$target::mach_vm_region:entry'               -n 'pid$target::task_for_pid:entry'              -c "$(pyenv which py-spy) -f o.svg -- python foo.py"
dtrace: system integrity protection is on, some features will not be available

dtrace: description 'pid$target::mach_vm_region:entry' matched 1 probe
dtrace: description 'pid$target::task_for_pid:entry' matched 2 probes
dtrace: pid 14131 has exited
CPU     ID                    FUNCTION:NAME
  5   4734               task_for_pid:entry
```

**Comment by spencerwilson-optimizely** [comment]
> Do you have any antivirus software running? Or is there any other major differences in the environment between your machines?

Good idea. I upgraded the other to the same version of macOS and ensured same version of Python and py-spy, and still the one works, one doesn't. There is an antivirus running, [Cb Defense](https://www.carbonblack.com/products/cb-defense/). Unfortunately, I can't turn it off without a trip over to our IT team (and even no guarantees then ;) ). I'll pitch it to them to try to test that hypothesis, though. I don't know anything about how antivirus software works, but that's kinda freaky if it can kill things without being observed by dtrace.

**Comment by crepererum** [comment]
I think I've seen this problem before 🤔
https://github.com/hishamhm/htop/issues/682

**Comment by benfred** [comment]
@crepererum I *think* that htop problem might be the same as this : https://jvns.ca/blog/2018/01/28/mac-freeze/ - which we should handle (with the sleep call here: https://github.com/rbspy/proc-maps/blob/96b274b826d7f9246856986af632b33672e9a7d9/src/mac_maps/mod.rs#L144  and I think apple has fixed the kernel bug in the macos version he's using). The htop issue is mentioned on this twitter thread about that post anyways: https://twitter.com/b0rk/status/957498366606368768

@spencerwilson-optimizely I think this program should reproduce the problem (without all the other rust/py-spy code getting in the way and confusing the issue):

```c++
// file: task_for_pid_test.cc
#include <mach/mach_init.h>
#include <mach/port.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, const char * argv[]) {
    if (argc <= 1) {
        printf("usage %s <pid>\n", argv[0]);
        return 1;
    }

    int pid = atoi(argv[1]);

    mach_port_name_t task = MACH_PORT_NULL;
    kern_return_t kr = task_for_pid(mach_task_self(), pid, &task);
    if (kr != KERN_SUCCESS) {
        printf("failed to call task_for_pid on pid %i: %x\n", pid, kr);
        return kr;
    }
    printf("success!\n");
    return 0;
}
```

compile with ```g++ task_for_pid_test.cc -o task_for_pid_test``` run with ```task_for_pid_test 12345``` where 12345 is your pid.

**Comment by spencerwilson-optimizely** [comment]
Yeah, it seems task_for_pid is fraught with peril: https://jvns.ca/blog/2018/01/28/mac-freeze/

In [this article](https://attilathedud.me/mac-os-x-el-capitan-10-11-and-task_for_pid/), the author claims that an `Info.plist` XML document has to be stashed inside the executable for the kernel to allow the system call. fwiw,
```
23:12 ~
$ strings $(pyenv which py-spy) | rg plist ; echo $?
1
```
Maybe the author's mistaken.

**Comment by benfred** [comment]
It's great that we figured out where it's happening - but I'm still not sure of why =(. 

It might be worth checking to see if you can disable your antivirus and try it out. I'm leaning towards it being a 3rd party program killing the process rather than something with os restrictions like SIP or taskgated (because I'd expect the task_for_pid call to fail rather than cause the process to get killed if this call is restricted by the OS). It still might be worth turning off SIP and verifying though.

Is there anything in the system log when this happens ? (Like open Console.app -> and checking system.log or /var/log). Or is there anything in the antivirus logs?

**Comment by spencerwilson-optimizely** [comment]
```
11:27 ~
$ tail -f /var/log/system.log | rg task_for_pid
# I run ./task_for_pid_test in another shell...
Sep 28 11:27:05 us-swilson CbDefense_Svc[8660]: The application "/Users/swilson/task_for_pid_test" attempted to open the process "python3.6" by calling the function "task_for_pid". The operation was blocked and the application terminated by CbDefense
```
Filed a ticket with our IT team.

**Comment by benfred** [comment]
awesome! glad we got to the bottom of this.
