### ISSUE TITLE
"No python processes found" for Python 3.10 on Windows

### ISSUE THREAD

**Issue by henriquegemignani** [benfred/py-spy#498]
The following command:
`py-spy top -s -- py -3.10 script.py`
Fails with `Error: No python processes found in process 3872 or any of its subprocesses`, while the script itself runs successfully.
If I instead run `py-spy top -s -- py -3.9 script.py`, it works perfectly.

Environment:
- Python 3.10.4
- Python 3.9.12
- py-spy 0.3.12
- Windows 11, build 10.0.22000

**Comment by windelbouwman** [comment]
I got a similar error:

     (.venv) C:\project>py-spy top -- python gui.py
    Error: Failed to find python version from target process

* Python 3.10.6
* py-spy 0.3.14
* Windows 10

**Comment by fleimgruber** [comment]
Also seeing this with Python 3.10.11

**Comment by tmct** [comment]
I'm afraid we still see the "No python processes" failure when using `--subprocesses`, using Python 3.10 from a virtual environment.

**Comment by sam-s** [comment]
on windows 10:
```
$ py-spy.exe dump --subprocesses --pid 20588
Error: Failed to find python version from target process
$ python --version
Python 3.12.7
$ py-spy.exe --version
py-spy 0.3.14
```
should I file a separate report?

**Comment by zanieb** [comment]
I don't think the 3.12 support has been released, it was just recently merged.

**Comment by benfred** [comment]
This should be fixed in the lastest release (0.4.0) - by https://github.com/benfred/py-spy/pull/543 and https://github.com/benfred/py-spy/pull/718.  

Can you try this out and re-open if the latest version doesn't fix for you?

**Comment by tim-stephenson** [comment]
I am on py-spy 0.4.0 and python 3.12 and still getting "Failed to find python version from target process" without the "-s" flag and "No python processes found in process <pid> or any of its subprocesses".

**Comment by tim-stephenson** [comment]
> I am on py-spy 0.4.0 and python 3.12 and still getting "Failed to find python version from target process" without the "-s" flag and "No python processes found in process <pid> or any of its subprocesses".

Looking into this more, I would guess this is due to other python 3.12 issues, as things seem to be working fine on python 3.10.
- #728
- #727
- #726

**Comment by oorjaa-sagar** [comment]
Coming from `pipenv`, I was able to make the following work on python 3.10 + windows:

```
pipenv run py-spy record -o base.svg -s -- python <script-name>.py
```
