### ISSUE TITLE
prebuilt binaries need glibc 2.18

### ISSUE THREAD

**Issue by Poil** [benfred/py-spy#5]
Hi,

The prebuilt binaries need glibc 2.18 and EL7 family have 2.17

```
py-spy: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by py-spy)
```
Best regards,

**Comment by JackLeo** [comment]
related to #16

**Comment by luser** [comment]
> I haven't thought deeply about the tradeoffs in this case, but maybe it makes sense to set TARGET=x86_64-unknown-linux-musl and similar to get a staticaly linked libc?

In case it's helpful, I configured Travis and AppVeyor to build binary releases of [sccache](https://github.com/mozilla/sccache) when I tag releases, and I'm building the Linux binaries against musl so they're more portable. Feel free to crib from my config files (and I'm happy to answer any questions you have, it took me a while to get this all working properly):
https://github.com/mozilla/sccache/blob/master/.travis.yml
https://github.com/mozilla/sccache/blob/master/appveyor.yml

**Comment by jgraham** [comment]
I probably should have mentioned that is also what we did for geckodriver:
https://github.com/mozilla/geckodriver/blob/release/.travis.yml
https://github.com/mozilla/geckodriver/blob/release/build.sh

(in case you need a second example to crib from :)

**Comment by benfred** [comment]
Thanks for the pointers @jgraham and @luser! I changed the linux wheels to use the musl toolchains instead, and this issue should be resolved in py-spy 0.1.5.

**Comment by mueslo** [comment]
I tried to run py-spy after pip-installing it on a raspberry pi running latest Raspbian/Raspberry Pi OS (Buster). 

I get 
```
$ py-spy
py-spy: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by py-spy)

$ ldd --version
ldd (Debian GLIBC 2.28-10+rpt2+rpi1) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

$ uname -a
Linux raspberrypi 5.10.63-v7+ #1457 SMP Tue Sep 28 11:25:31 BST 2021 armv7l GNU/Linux
```

**Comment by benfred** [comment]
@mueslo I don't maintain the package at ```https://www.piwheels.org/simple/py-spy/py_spy-0.3.10-py3-none-linux_armv7l.whl``` . I'm guessing if you want to use this, you'll have to also install libunwind-ptrace through something like ```sudo apt-get install libunwind-dev```, since the dependencies aren't getting bundled with the package at piwheels.org.
 
The armv7 packages we have on pypi (https://pypi.org/project/py-spy/#files) will have a statically linked version of all dependencies, including libc/libunwind-ptrace though - and should work without installing any extras.
