### ISSUE TITLE
Error: Failed to find a python interpreter in the .data section

### ISSUE THREAD

**Issue by danielhrisca** [benfred/py-spy#516]
Hello,

I get this error  with the following environment:
* Windows 10 x64
* CPython 3.10.5 x64 using the [WinPython distribution](https://github.com/winpython/winpython/releases/download/4.7.20220709final/Winpython64-3.10.5.0dot.exe)
* py-spy 0.3.12

Any ideas? Thank you!

**Comment by danielhrisca** [comment]
The `pdb` files were missing from the WinPython distribution. 
![image](https://user-images.githubusercontent.com/20952040/183608933-eed28fb6-8580-42d5-bfb0-db58a27a2ba2.png)

I've added them and now the error is gone (I got them by installing the official cpython and selecting to download the debugging files, then copying the `pdb` files into the WinPython folder

![image](https://user-images.githubusercontent.com/20952040/183609186-7af1baf3-4d77-48e5-87b8-0858f61ed3ac.png)

**Comment by secsilm** [comment]
I get the same error on Ubuntu, python3.8, py-spy0.3.14. Any suggestions to solve this? BTW I have found the pdb file:

![image](https://user-images.githubusercontent.com/8894643/211229264-e75997db-34e9-4439-b83c-7cff300c3615.png)

**Comment by OneSizeFitsQuorum** [comment]
Install debugging symbols works for me!!!
![image](https://user-images.githubusercontent.com/32640567/224034263-581ebfb9-d341-4678-b750-00468a44b215.png)

**Comment by mugbya** [comment]
> Install debugging symbols works for me!!! ![image](https://user-images.githubusercontent.com/32640567/224034263-581ebfb9-d341-4678-b750-00468a44b215.png)

thank you !!!! It's useful
