### ISSUE TITLE
How could I view the average time taken for a function?

### ISSUE THREAD

**Issue by roger12023** [benfred/py-spy#519]
Im using it with speedscope, It took me a day to check the documentations and try out some experiment to fail to get the average time per functions, in the graph as below there are two functions, since the time taken is for the purple/green functions varies over time, it would be nice to know what is the average time cost for functions. 

Please shed me some light over it, I look forward to your replies. Thanks

![image](https://user-images.githubusercontent.com/52447418/188269327-29dc4dd2-50c6-43e7-b34e-527b87ecaacb.png)

**Comment by Jongy** [comment]
py-spy is a sampling profiler. It doesn't trace your program and it doesn't know "how much time" things takes. The resulting profile of py-spy gives you the relative distribution of samples  spent in different areas of your code (and logically, the relative distribution of time). But if a function takes, say, 10% of a profile of 10 seconds, you can't know if it ran for one full second, or if it ran a million times during that one second.

If you want to get "how much time" you can use a tracing profiler like cProfile, which can measure the number of executions of a function, and the cumulative duration, etc.

**Comment by roger12023** [comment]
I got it, thanks 

> py-spy is a sampling profiler. It doesn't trace your program and it doesn't know "how much time" things takes. The resulting profile of py-spy gives you the relative distribution of samples spent in different areas of your code (and logically, the relative distribution of time). But if a function takes, say, 10% of a profile of 10 seconds, you can't know if it ran for one full second, or if it ran a million times during that one second.
> 
> If you want to get "how much time" you can use a tracing profiler like cProfile, which can measure the number of executions of a function, and the cumulative duration, etc.

Thanks Jongy for the extensive explanation.

**Comment by Jongy** [comment]
You're welcome :)
