### ISSUE TITLE
OS cannot find binary when installed in a pyenv-managed virtualenv

### ISSUE THREAD

**Issue by kennes913** [benfred/py-spy#53]
I am working on an EC2 instance using a version of pyenv compiled from the github repo. 

When I `pip install py-spy`, everything looks fine, but when I run `py-spy --pid xxxx`, it fails to find the binary. 

I assumed this was a python package so I ran `python -c "import sys; print(sys.path)"` to verify my system path to see where py-spy should be if I were loading it into a interpreter and py-spy is nowhere to be found on any of those paths which are:

```
['',
 '{HOME}/.pyenv/versions/3.6.3/lib/python36.zip',
 '{HOME}/.pyenv/versions/3.6.3/lib/python3.6',
 '{HOME}/.pyenv/versions/3.6.3/lib/python3.6/lib-dynload',
 '{HOME}/.pyenv/versions/{my_virtual_env}/lib/python3.6/site-packages']
 ```
I also looked in:
```
{HOME}/.pyenv/shims/
```
and had no luck. Instead it's located here:
```
 {HOME}/.pyenv/versions/3.6.3/envs/{my_virtual_env}/bin/py-spy
```
Is this the intended behavior? Did I mess something up? Or should this be placed on the `.pyenv/shims/*` path?

I'm obviously using python 3.6.3 and working on Linux AMI. 

If it helps, pyenv was installed from the Github repo not Homebrew. Also, this worked on my mac which is running the pyenv homebrew version and py-spy installed to:
```
{HOME}/.pyenv/shims/py-spy
```

**Comment by benfred** [comment]
pip should be installing py-spy to the  bin directory of your python install, which looks correct from the info you gave.  The weird part is that your bin directory for your python environment isn't on your path.

What happens if you install other command-line python scripts? Like if you go ```pip install flake8``` does it install flake8 to the same bin directory?

Also, are you using sudo to run py-spy? (like did you install as one user, and then try running as another?). If so the path might be different between users - you can do something like ```sudo env "PATH=$PATH" py-spy --pid 12345``` if that is the case

**Comment by kennes913** [comment]
> What happens if you install other command-line python scripts? Like if you go pip install flake8 does it install flake8 to the same bin directory?

Yep, I have flake8 installed and it exists in that directory. 

> Also, are you using sudo to run py-spy? (like did you install as one user, and then try running as another?)

Nope. 

It sounds like I may have messed something up.

**Comment by benfred** [comment]
Hmm, yeah it sounds like something is messed up =( I don't have any great suggestions unfortunately, aside from making sure that the virtualenv is activated ```source my_virtual_env/bin/activate``` . 

You could also install py-spy to the system python (```/usr/bin/pip install py-spy``` - py-spy handles multiple versions so doesn't need to be installed by the same version of python that you want to profile.

**Comment by kennes913** [comment]
Hm, okay, temporarily going to append that `/bin` directory onto path.
