### ISSUE TITLE
Invalid pid: ParseIntError

### ISSUE THREAD

**Issue by jonathan-s** [benfred/py-spy#54]
I'm getting the following error 

```
thread 'main' panicked at 'invalid pid: ParseIntError { kind: InvalidDigit }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

When I'm running `py-spy -pid 20`

**Comment by jonathan-s** [comment]
It's a documentation error, it should be `py-spy --pid 20`

**Comment by benfred** [comment]
Fixed here https://github.com/benfred/py-spy/commit/213389ce17c013b1308bde7c440fb8ca10ce0c9c - thanks for the heads up!
