### ISSUE TITLE
Install fails on Win 10

### ISSUE THREAD

**Issue by developing-coder** [benfred/py-spy#55]
I'm getting the following error message. Please let me know if I can provide any additional information.

Python 3.7.0 and 3.7.1. Pip 18.0 and 18.1. Win 10 64-bit.

```
Could not find a version that satisfies the requirement py-spy (from versions: )
No matching distribution found for py-spy
```

**Comment by benfred** [comment]
I think the most likely cause of this is using a 32 bit version of Python - which py-spy doesn't handle right now on windows.  

What does this print out?
```
python -c 'import platform; print(platform.architecture())''
```

**Comment by developing-coder** [comment]
Good guess. `platform.architecture()` does print `32bit` and install works after upgrading to `64bit` Python.

Thanks!
