### ISSUE TITLE
`--native`

### ISSUE THREAD

**Issue by w14** [benfred/py-spy#646]
The docs state:

> py-spy supports profiling native python extensions written in languages like C/C++ or Cython, on x86_64 Linux and Windows. You can enable this mode by passing --native on the command line. 

How should it be called? Try a simple program:

```
py-spy record --native -o profile.svg -- python3 test.py
```

And I got the error "unrecognized flag".

**Comment by benfred** [comment]
Hmm, this should work (at least on x86_64 Linux and windows)

What operating system are you using?  Also what kind of cpu is this on?

**Comment by peekxc** [comment]
Can confirm this doesn't work on OS X (x86_64)
