### ISSUE TITLE
No source distribution files available in the Pypi site

### ISSUE THREAD

**Issue by mkumatag** [benfred/py-spy#655]
I don't see a source distribution for this package in the Pypi site

<img width="1261" alt="image" src="https://github.com/benfred/py-spy/assets/12646029/583ee612-8e54-4765-b090-e7869a6a7566">

link to the PyPi - https://pypi.org/project/py-spy/#files

This is blocking me to do a pip install on the platform for which we aren't shipping the wheels.

Any help is appreciated @benfred

**Comment by mkumatag** [comment]
related - https://github.com/benfred/py-spy/issues/575

**Comment by benfred** [comment]
there is a sdist package up on pypi with the latest release https://pypi.org/project/py-spy/#files
