### ISSUE TITLE
unresolved import `winapi::um::errhandlingapi`

### ISSUE THREAD

**Issue by SEBROVATER** [benfred/py-spy#668]
Installing through `pip` works fine, but installing through `cargo` fails with a compile error.

The full error message looks like this:
```
error[E0432]: unresolved import `winapi::um::errhandlingapi`
  --> C:\Users\sebro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\remoteprocess-0.4.13\src\windows\symbolication.rs:11:17
   |
11 | use winapi::um::errhandlingapi::GetLastError;
   |                 ^^^^^^^^^^^^^^ could not find `errhandlingapi` in `um`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `remoteprocess` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `py-spy v0.3.14`, intermediate artifacts can be found at `C:\Users\sebro\AppData\Local\Temp\cargo-installmeg7Lx`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

The same error appears if I try to compile from the source (main branch)

System info:
Windows 11 Home (fresh installation, as I bought a new laptop)
`cargo --version` 1.78.0 (54d8815d0 2024-03-26)
`rustc --version` 1.78.0 (9b00956e5 2024-04-29
Used "Sophia-Script for Windows" to clear the system from useless garbage, maybe it caused some problems.

**Comment by akhramov** [comment]
https://github.com/benfred/remoteprocess/pull/88

A fix for this ^

**Comment by benfred** [comment]
believe this is fixed by https://github.com/benfred/py-spy/pull/685
