### ISSUE TITLE
Cannot detect GIL holding

### ISSUE THREAD

**Issue by satyamg1620** [benfred/py-spy#669]
Cannot detect GIL holding in version '3.9.18' on the current platform (reason: unknown pyruntime.gilstate.tstate_current offset)
Python version: 3.9.18
Platform: s390x

**Comment by satyamg1620** [comment]
@simonrw @benfred @jarus @auscompgeek can you please help with this issue?

**Comment by benfred** [comment]
GIL detection is platform dependant for py-spy when profiling python versions before 3.12 - and we don't officially support the s390x platform. This isn't something we'll be able to help out with unfortunately
