### ISSUE TITLE
Continued Maintenance and Development

### ISSUE THREAD

**Issue by hendrikmakait** [benfred/py-spy#683]
`py-spy` has been an invaluable tool for me when investigating the performance of projects like Dask, but unfortunately, it looks like activity on this repository has died down. I would love to see improved support for Python 3.11 released and support for 3.12 finished. 

@benfred, I realize that other things are probably a higher priority for you. Would you be open to others (like me) stepping up and handling maintenance and continued development? I would love to help make this project survive and prosper.

**Comment by zanieb** [comment]
I would also be interested in helping out (with relevant experience as a maintainer of `python-build-standalone`, `ruff`, and `uv` as well as some contributions here a while ago).

**Comment by zanieb** [comment]
I'm going to start hacking on this in my spare time at https://github.com/zanieb/py-spy/pull/9 — feel free to take anything from there or let me know if you'd accept them as pull requests here.

**Comment by dovreshef** [comment]
I've updated all deps & fixed clippy warnings in my fork (https://github.com/dovreshef/py-spy).

I also want to support python 3.12/3.13 and would love to chip in and help..

**Comment by zanieb** [comment]
Ben's making a lot of progress on the backlog here! Thank you :)
