### ISSUE TITLE
cannot use py-spy with --native option

### ISSUE THREAD

**Issue by zuquan-song** [benfred/py-spy#697]
hey, I use `maturin build` to build py-spy on linux, but the binary does not show --native option. Anyone could help answer my question?

**Comment by zuquan-song** [comment]
BTW, is there any plan to release 0.3.15? I want the new py-spy to dump native frames on python 3.11

**Comment by zanieb** [comment]
@zuquan-song you'll need to include the `--feature unwind` option during build.

**Comment by zuquan-song** [comment]
> @zuquan-song you'll need to include the `--feature unwind` option during build.

Thanks! Are there any other options needed to build a whl that has the same features as 0.3.14?

**Comment by zanieb** [comment]
I don't think so

**Comment by zuquan-song** [comment]
@zanieb When I try to build with `--features unwind`, it has another issue
```
error[E0609]: no field `addr` on type `&BinaryInfo`
  --> src/binary_parser.rs:18:22
   |
18 |         addr >= self.addr && addr < (self.addr + self.size)
   |                      ^^^^ unknown field
   |
   = note: available fields are: `symbols`, `bss_addr`, `bss_size`

error[E0609]: no field `addr` on type `&BinaryInfo`
  --> src/binary_parser.rs:18:43
   |
18 |         addr >= self.addr && addr < (self.addr + self.size)
   |                                           ^^^^ unknown field
   |
   = note: available fields are: `symbols`, `bss_addr`, `bss_size`

error[E0609]: no field `size` on type `&BinaryInfo`
  --> src/binary_parser.rs:18:55
   |
18 |         addr >= self.addr && addr < (self.addr + self.size)
   |                                                       ^^^^ unknown field
   |
   = note: available fields are: `symbols`, `bss_addr`, `bss_size`

For more information about this error, try `rustc --explain E0609`.
```

Do you know how to fix that?

**Comment by zanieb** [comment]
You need a newer commit, https://github.com/benfred/py-spy/pull/688

**Comment by benfred** [comment]
going to close this issue - please re-open if you're still having issues!
