### ISSUE TITLE
Additional dependency on perl

### ISSUE THREAD

**Issue by Turidus** [benfred/py-spy#7]
I found a small hiccup:
When using py-spy with the -flame option, it also depends on Perl. Not having any Perl installation, trying to execute -flame netted me a "Could not execute Perl. File not found [oserror 2]" error. After installing Perl it functioned flawlessly.

Would be cool if this dependency could be mentioned in the readme to make troubleshooting easier.

**Comment by benfred** [comment]
good point! It should probably also mention that you need to install perl in the error message too if it's missing.

**Comment by benfred** [comment]
We're removing the perl dependency altogether: https://github.com/benfred/py-spy/pull/114
