### ISSUE TITLE
py-spy 0.1.9 doesn't create flamegraphs

### ISSUE THREAD

**Issue by rcoh** [benfred/py-spy#70]
`--flame out.svg` doesn't actually produce a flamegraph (no errors or other debug output is produced)

`pip install py-spy==0.1.8` fixes the issue. Seems like a pretty major regression -- may want to pull the most recent release from PyPI

**Comment by benfred** [comment]
Also, can you let me know if v0.1.10 also has this problem? This release fixes a bug I introduced in v0.1.9 - and I'm wondering if your issues are related

**Comment by rcoh** [comment]
Hmm, debian stretch. Will verify and get back to you
