### ISSUE TITLE
Inspect local variables

### ISSUE THREAD

**Issue by guettli** [benfred/py-spy#77]
First: Thank you very much for this great tool.

Is it possible to look at the local variables of a frame?

This would be awesome.

In my case I see that a django process is executing a sql statement which takes long.

It would be very nice if I could see the sql statement.

What do you think?

**Comment by benfred** [comment]
I've added some basic ability to do this in #176 - if you pass in ```--locals``` to the dump command now it will print out the local variables associated with each frame. It's limited to combinations of str/float/int/bool/nonetype/list/tuple/dict objects - but could still be pretty helpful for lightweight debugging .

**Comment by guettli** [comment]
@benfred  thank you very much!

**Comment by benfred** [comment]
This change is in v0.2.2 - it looks something like:

<img width="782" alt="localvars" src="https://user-images.githubusercontent.com/69536/66370589-a5859d80-e955-11e9-821c-e06d6185bdf0.png">

**Comment by benfred** [comment]
uggh - just tried this out on Linux and there are some remaining issues so I'm reopening this:

1) This messes up the thread idle detection logic (which is visible in the screenshot above with the thread being marked as idle).
2) This doesn't work with the native profiling option.

**Comment by benfred** [comment]
fix is here:  https://github.com/benfred/py-spy/pull/180
