### ISSUE TITLE
invoke from command line without python in the system path [windows, py-launcher]

### ISSUE THREAD

**Issue by terrdavis** [benfred/py-spy#78]
**As a** Windows user  
**I want** a module based invocation  
**So that** I can run the script with the py-launcher  

Here's a script that does this:
Contents of `C:\python37\lib\site-packages\py_spy.py`:
```python
import subprocess
import sys

try:
    subprocess.call([f'{sys.exec_prefix}/Scripts/py-spy.exe'] + sys.argv[1:])
except KeyboardInterrupt:
    pass
```
Usage:
```
py -m py_spy [args]
```

**Comment by benfred** [comment]
see https://github.com/benfred/py-spy/issues/80 for fix
