### ISSUE TITLE
Error while trying to run in Kubernetes

### ISSUE THREAD

**Issue by achanda** [benfred/py-spy#8]
I got this error while trying to profile in a pod in Kubernetes
```
root@pomegranate-deployment-6844867c8c-49mtx:/app# py-spy --pid 13
Permission Denied: Try running again with elevated permissions by going 'sudo env "PATH=$PATH" !!'
```
I suspect it needs some kernel capability that is filtered out by default. Any idea which ones does it need?

**Comment by JuxhinDB** [comment]
Well the [README](https://github.com/benfred/py-spy#when-do-you-need-to-run-as-sudo) seems to state that you're going to need elevated privileges to access process memory. Are you able to run it with `sudo`?

**Comment by achanda** [comment]
Running it with `sudo` did not work. I had to add `CAP_SYS_PTRACE` to the pod to make it work.

**Comment by achanda** [comment]
I had to add a new capability under `Deployment.spec.template.spec.containers` using this:
```
securityContext:
  capabilities:
    add:
    - SYS_PTRACE
```

**Comment by benfred** [comment]
Instructions on running with kubernetes were added here https://github.com/benfred/py-spy/pull/17
