### ISSUE TITLE
Support invocation with python_program argument from py-launcher [windows]

### ISSUE THREAD

**Issue by terrdavis** [benfred/py-spy#80]
**As a** Windows user  
**I want** to use py-launcher as the python_program argument  
**So that** I can run the script without Python in PATH  

This doesn't work:
`C:\python37\scripts\py-spy.exe py myscript.py`

So I have to do this:
`C:\python37\scripts\py-spy.exe C:\python37\python.exe myscript.py`

With #78 implemented, this would work:
`py -m py_spy py myscript.py`

**Comment by benfred** [comment]
The latest version of py-spy has the ability to profile subprocesses - so you can profile py-launcheer by going```py-spy top -s py myscript.py```, and py-spy will attach to the python process that py-launcher creates
