### ISSUE TITLE
os error 299 on Windows 10

### ISSUE THREAD

**Issue by asypost** [benfred/py-spy#9]
When I run py-spy -- python xx.py,I got a os error 299,I also try run it with administrator but get the same error.
Windows Version:10 64bit
Python Version:3.6.6 64bit

**Comment by benfred** [comment]
hmm - everytime I've seen error 299 on windows, it has meant that the profiled process has exited. 

Can you try enabling logging and pasting the output here? 

```
set RUST_LOG=info
py-spy -- python xx.py
```

**Comment by Tjorriemorrie** [comment]
In cygwin on py2.7
```
$ set RUST_LOG=info
$ py-spy --pid 5416
Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
```
I don't see any logs?

**Comment by asypost** [comment]
@benfred I got the output:

>  INFO 2018-09-07T01:08:01Z: py_spy: Command line args: ArgMatches { args: {"rate": MatchedArg { occurs: 0, indices: [3], vals: ["1000"] }, "duration": MatchedArg { occurs: 0, indices: [4], vals: ["2"] }, "python_program": MatchedArg { occurs: 2, indices: [1, 2], vals: ["python", "xx.py"] }}, subcommand: None, usage: Some("USAGE:\n    py-spy [FLAGS] [OPTIONS] --pid <pid> [python_program]...") }
 INFO 2018-09-07T01:08:01Z: py_spy::python_spy: Failed to connect to process, retrying. Error: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。 (os error 299)
 INFO 2018-09-07T01:08:01Z: py_spy::python_spy: Failed to connect to process, retrying. Error: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。 (os error 299)
 INFO 2018-09-07T01:08:01Z: py_spy::python_spy: Failed to connect to process, retrying. Error: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。 (os error 299)
 INFO 2018-09-07T01:08:01Z: py_spy::python_spy: Failed to connect to process, retrying. Error: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。 (os error 299)
 INFO 2018-09-07T01:08:02Z: py_spy::python_spy: Failed to connect to process, retrying. Error: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。 (os error 299)
 INFO 2018-09-07T01:08:02Z: py_spy::python_spy: Failed to connect to process, retrying. Error: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。 (os error 299)
 INFO 2018-09-07T01:08:02Z: py_spy::python_spy: Failed to connect to process, retrying. Error: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。 (os error 299)

Error: 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。 (os error 299)

**Comment by wailashi** [comment]
I'm getting the same error.
Windows 7 64 bit.
Python 3.6.6
py-spy 0.1.5 installed via pip

```
(venv) C:\Users\MLCA\PycharmProjects\py-spy-test>set RUST_LOG=info
(venv) C:\Users\MLCA\PycharmProjects\py-spy-test>py-spy -- python test.py
 INFO 2018-09-11T07:07:07Z: py_spy: Command line args: ArgMatches { args: {"rate": MatchedArg { occurs: 0, indices: [3], vals: ["1000"] }, "duration": MatchedArg { occurs: 0, indices: [
4], vals: ["2"] }, "python_program": MatchedArg { occurs: 2, indices: [1, 2], vals: ["python", "test.py"] }}, subcommand: None, usage: Some("USAGE:\n    py-spy [FLAGS] [OPTIONS] --pid <
pid> [python_program]...") }
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: Failed to connect to process, retrying. Error: The program issued a command but the command length is incorrect. (os error 24)
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: Got virtual memory maps from pid 11184:
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 000000001c420000-000000001c43b000 rwx C:\Users\MLCA\PycharmProjects\py-spy-test\venv\Scripts\python.exe
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000077c20000-0000000077da0000 rwx C:\WINDOWS\SysWOW64\ntdll.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000077640000-0000000077750000 rwx C:\WINDOWS\syswow64\kernel32.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 00000000761f0000-0000000076237000 rwx C:\WINDOWS\syswow64\KERNELBASE.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 000000001d200000-000000001d543000 rwx C:\Users\MLCA\PycharmProjects\py-spy-test\venv\Scripts\python36.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000074ad0000-0000000074ad9000 rwx C:\WINDOWS\system32\VERSION.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000076e00000-0000000076eac000 rwx C:\WINDOWS\syswow64\msvcrt.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000077290000-00000000772e7000 rwx C:\WINDOWS\syswow64\SHLWAPI.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000076d70000-0000000076e00000 rwx C:\WINDOWS\syswow64\GDI32.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 00000000774a0000-00000000775a0000 rwx C:\WINDOWS\syswow64\USER32.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 00000000771e0000-0000000077281000 rwx C:\WINDOWS\syswow64\ADVAPI32.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000076720000-0000000076739000 rwx C:\WINDOWS\SysWOW64\sechost.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000076630000-0000000076720000 rwx C:\WINDOWS\syswow64\RPCRT4.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 00000000754d0000-0000000075530000 rwx C:\WINDOWS\syswow64\SspiCli.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 00000000754c0000-00000000754cc000 rwx C:\WINDOWS\syswow64\CRYPTBASE.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000076180000-000000007618a000 rwx C:\WINDOWS\syswow64\LPK.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000076a50000-0000000076aed000 rwx C:\WINDOWS\syswow64\USP10.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000076ef0000-0000000076f25000 rwx C:\WINDOWS\syswow64\WS2_32.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000076af0000-0000000076af6000 rwx C:\WINDOWS\syswow64\NSI.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 000000006cbf0000-000000006cc05000 rwx C:\Users\MLCA\PycharmProjects\py-spy-test\venv\Scripts\VCRUNTIME140.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000069f20000-0000000069f24000 rwx C:\WINDOWS\system32\api-ms-win-crt-runtime-l1-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000067760000-0000000067840000 rwx C:\WINDOWS\system32\ucrtbase.DLL
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000069ee0000-0000000069ee3000 rwx C:\WINDOWS\system32\api-ms-win-core-timezone-l1-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000069ed0000-0000000069ed3000 rwx C:\WINDOWS\system32\api-ms-win-core-file-l2-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000069ea0000-0000000069ea3000 rwx C:\WINDOWS\system32\api-ms-win-core-localization-l1-2-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 000000006c810000-000000006c813000 rwx C:\WINDOWS\system32\api-ms-win-core-synch-l1-2-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000069e90000-0000000069e93000 rwx C:\WINDOWS\system32\api-ms-win-core-processthreads-l1-1-1.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000069e80000-0000000069e83000 rwx C:\WINDOWS\system32\api-ms-win-core-file-l1-2-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000069e70000-0000000069e74000 rwx C:\WINDOWS\system32\api-ms-win-crt-string-l1-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000069e60000-0000000069e63000 rwx C:\WINDOWS\system32\api-ms-win-crt-heap-l1-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000068bf0000-0000000068bf4000 rwx C:\WINDOWS\system32\api-ms-win-crt-stdio-l1-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000068be0000-0000000068be4000 rwx C:\WINDOWS\system32\api-ms-win-crt-convert-l1-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000067750000-0000000067755000 rwx C:\WINDOWS\system32\api-ms-win-crt-math-l1-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000067740000-0000000067743000 rwx C:\WINDOWS\system32\api-ms-win-crt-locale-l1-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000067730000-0000000067733000 rwx C:\WINDOWS\system32\api-ms-win-crt-time-l1-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000067720000-0000000067723000 rwx C:\WINDOWS\system32\api-ms-win-crt-environment-l1-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000067710000-0000000067713000 rwx C:\WINDOWS\system32\api-ms-win-crt-process-l1-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000067700000-0000000067703000 rwx C:\WINDOWS\system32\api-ms-win-crt-conio-l1-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 00000000676f0000-00000000676f3000 rwx C:\WINDOWS\system32\api-ms-win-crt-filesystem-l1-1-0.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 00000000765d0000-0000000076630000 rwx C:\WINDOWS\system32\IMM32.DLL
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000076fc0000-000000007708d000 rwx C:\WINDOWS\syswow64\MSCTF.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000074880000-0000000074897000 rwx C:\WINDOWS\system32\CRYPTSP.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: map: 0000000074840000-000000007487b000 rwx C:\WINDOWS\system32\rsaenh.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: Found python binary @ C:\Users\MLCA\PycharmProjects\py-spy-test\venv\Scripts\python.exe
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: Found libpython binary @ C:\Users\MLCA\PycharmProjects\py-spy-test\venv\Scripts\python36.dll
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: Getting version from python binary BSS
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: Failed to get version from BSS section: failed to find version string
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: Getting version from libpython BSS
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: Found matching version string '3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (I'
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: python version 3.6.6 detected
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: Failed to get interp_head from symbols, scanning BSS section from main binary
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: Failed to get interpreter from binary BSS, scanning libpython BSS
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: Found interpreter at 0x0000000000888e38
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: Found _PyThreadState_Current @ 0x000000001d508550
 INFO 2018-09-11T07:07:09Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 29
9)
```
The error message repeats several times, for brevity I have only included the head of the log.
test.py is a simple hello world script.

**Comment by benfred** [comment]
@Tjorriemorrie you need to set the RUST_LOG environment variable to info. ```set RUST_LOG=info``` is valid for cmd.exe, on cygwin it might be something like ```export RUST_LOG=info```

@wailashi It looks like you are using a 32 bit python install. This doesn't work yet on windows, I've created a new issue here to track : https://github.com/benfred/py-spy/issues/31

@asypost I'm still not sure why this isn't working for you, I'm going to add some more logging to help out here later today.

**Comment by jgergo** [comment]
Hi!

I have the same (os error 299) issue. 

im on python 3.7.0
in a separate venv for the project
Windows 10 64 bit

the log message:

INFO 2018-09-11T14:20:09Z: py_spy: Command line args: ArgMatches { args: {"python_program": MatchedArg { occurs: 2, indices: [1, 2], vals: ["python", "version.py"] }, "rate": MatchedArg { occurs: 0, indices: [3], vals: ["1000"] }, "duration": MatchedArg { occu
rs: 0, indices: [4], vals: ["2"] }}, subcommand: None, usage: Some("USAGE:\n    py-spy [FLAGS] [OPTIONS] --pid <pid> [python_program]...") }
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Got virtual memory maps from pid 37344:
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000001210000-000000000122a000 rwx C:\_repos\aadpackages\AAD_ExcelChecker\venv\Scripts\python.exe
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 00007ffc44500000-00007ffc446e1000 rwx C:\WINDOWS\SYSTEM32\ntdll.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000077310000-0000000077362000 rwx C:\WINDOWS\System32\wow64.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000077290000-0000000077308000 rwx C:\WINDOWS\System32\wow64win.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000077280000-000000007728a000 rwx C:\WINDOWS\System32\wow64cpu.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000001210000-000000000122a000 rwx C:\_repos\aadpackages\AAD_ExcelChecker\venv\Scripts\python.exe
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000077370000-0000000077500000 rwx C:\WINDOWS\SysWOW64\ntdll.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000076750000-0000000076830000 rwx C:\WINDOWS\SysWOW64\KERNEL32.DLL
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000074350000-0000000074534000 rwx C:\WINDOWS\SysWOW64\KERNELBASE.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000076dd0000-0000000076eee000 rwx C:\WINDOWS\SysWOW64\ucrtbase.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 00000000705a0000-00000000705b5000 rwx C:\_repos\aadpackages\AAD_ExcelChecker\venv\Scripts\VCRUNTIME140.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 000000000f870000-000000000fc0b000 rwx C:\_repos\aadpackages\AAD_ExcelChecker\venv\Scripts\python37.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 00000000766e0000-0000000076725000 rwx C:\WINDOWS\SysWOW64\SHLWAPI.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000077130000-00000000771ef000 rwx C:\WINDOWS\SysWOW64\msvcrt.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000073bc0000-0000000073bc8000 rwx C:\WINDOWS\SysWOW64\VERSION.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000076b70000-0000000076dcc000 rwx C:\WINDOWS\SysWOW64\combase.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000076610000-00000000766d0000 rwx C:\WINDOWS\SysWOW64\RPCRT4.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000073c30000-0000000073c50000 rwx C:\WINDOWS\SysWOW64\SspiCli.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000073c20000-0000000073c2a000 rwx C:\WINDOWS\SysWOW64\CRYPTBASE.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000076340000-0000000076398000 rwx C:\WINDOWS\SysWOW64\bcryptPrimitives.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000076ef0000-0000000076f34000 rwx C:\WINDOWS\SysWOW64\sechost.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000076f40000-0000000076f62000 rwx C:\WINDOWS\SysWOW64\GDI32.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 00000000763a0000-0000000076504000 rwx C:\WINDOWS\SysWOW64\gdi32full.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000073c70000-0000000073ced000 rwx C:\WINDOWS\SysWOW64\msvcp_win.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000076930000-0000000076abd000 rwx C:\WINDOWS\SysWOW64\USER32.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000076730000-0000000076747000 rwx C:\WINDOWS\SysWOW64\win32u.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000077210000-0000000077277000 rwx C:\WINDOWS\SysWOW64\WS2_32.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 00000000742d0000-0000000074348000 rwx C:\WINDOWS\SysWOW64\ADVAPI32.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000076310000-0000000076336000 rwx C:\WINDOWS\SysWOW64\IMM32.DLL
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000072280000-0000000072293000 rwx C:\WINDOWS\SysWOW64\CRYPTSP.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000072250000-000000007227f000 rwx C:\WINDOWS\SysWOW64\rsaenh.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: map: 0000000072c50000-0000000072c69000 rwx C:\WINDOWS\SysWOW64\bcrypt.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Found python binary @ C:\_repos\aadpackages\AAD_ExcelChecker\venv\Scripts\python.exe
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Found libpython binary @ C:\_repos\aadpackages\AAD_ExcelChecker\venv\Scripts\python37.dll
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Getting version from python binary BSS
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Failed to get version from BSS section: failed to find version string
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Getting version from libpython BSS
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Found matching version string '3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (I'
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: python version 3.7.0 detected
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Found interpreter at 0x0fb52a8c00000000
 WARN 2018-09-11T14:20:09Z: py_spy::python_spy: Failed to find _PyThreadState_Current symbol - won't be able to detect GIL usage
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Failed to copy PyInterpreterState from process
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
 INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
version: 0.0.0.0 -> branch: local

Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)

**Comment by benfred** [comment]
@jgergo you're also running a 32 bit python =(
```
INFO 2018-09-11T14:20:09Z: py_spy::python_spy: Found matching version string '3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (I'
```

**Comment by jgergo** [comment]
Thanks @benfred , i saw the 32bit issue just after submitting my comment. Gonna check 64 python now.

**Comment by jgergo** [comment]
i have the same issue with 64 bit python 3.7

either using the --pid <pid> or the python <filename>

```
 INFO 2018-09-11T15:46:17Z: py_spy: Command line args: ArgMatches { args: {"python_program": MatchedArg { occurs: 2, indices: [1, 2], vals: ["python", "version.py"] }, "duration": MatchedArg { occurs: 0, indices: [4], vals: ["2"] }, "rate": MatchedArg { occurs:
 0, indices: [3], vals: ["1000"] }}, subcommand: None, usage: Some("USAGE:\n    py-spy [FLAGS] [OPTIONS] --pid <pid> [python_program]...") }
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: Got virtual memory maps from pid 9828:
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007ff613400000-00007ff61341b000 rwx C:\_repos\aadpackages\AAD_ExcelChecker\venv\Scripts\python.exe
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4fdd0000-00007fff4ffb1000 rwx C:\WINDOWS\SYSTEM32\ntdll.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4f430000-00007fff4f4e2000 rwx C:\WINDOWS\System32\KERNEL32.DLL
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4c610000-00007fff4c883000 rwx C:\WINDOWS\System32\KERNELBASE.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4ca00000-00007fff4cafa000 rwx C:\WINDOWS\System32\ucrtbase.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff27650000-00007fff27a26000 rwx C:\_repos\aadpackages\AAD_ExcelChecker\venv\Scripts\python37.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff47850000-00007fff47866000 rwx C:\_repos\aadpackages\AAD_ExcelChecker\venv\Scripts\VCRUNTIME140.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4f6a0000-00007fff4f6f1000 rwx C:\WINDOWS\System32\SHLWAPI.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4eff0000-00007fff4f08e000 rwx C:\WINDOWS\System32\msvcrt.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4f700000-00007fff4fa23000 rwx C:\WINDOWS\System32\combase.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff463c0000-00007fff463ca000 rwx C:\WINDOWS\SYSTEM32\VERSION.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4faa0000-00007fff4fbc4000 rwx C:\WINDOWS\System32\RPCRT4.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4c340000-00007fff4c3ba000 rwx C:\WINDOWS\System32\bcryptPrimitives.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4fbd0000-00007fff4fbf8000 rwx C:\WINDOWS\System32\GDI32.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4c1a0000-00007fff4c332000 rwx C:\WINDOWS\System32\gdi32full.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4c960000-00007fff4c9ff000 rwx C:\WINDOWS\System32\msvcp_win.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4d780000-00007fff4d910000 rwx C:\WINDOWS\System32\USER32.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4c890000-00007fff4c8b0000 rwx C:\WINDOWS\System32\win32u.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4fa30000-00007fff4fa9c000 rwx C:\WINDOWS\System32\WS2_32.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4fcf0000-00007fff4fd91000 rwx C:\WINDOWS\System32\ADVAPI32.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4f090000-00007fff4f0eb000 rwx C:\WINDOWS\System32\sechost.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4efc0000-00007fff4efed000 rwx C:\WINDOWS\System32\IMM32.DLL
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4bb20000-00007fff4bb37000 rwx C:\WINDOWS\SYSTEM32\CRYPTSP.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4b540000-00007fff4b573000 rwx C:\WINDOWS\system32\rsaenh.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4bc40000-00007fff4bc65000 rwx C:\WINDOWS\SYSTEM32\bcrypt.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: map: 00007fff4bb10000-00007fff4bb1b000 rwx C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: Found python binary @ C:\_repos\aadpackages\AAD_ExcelChecker\venv\Scripts\python.exe
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: Found libpython binary @ C:\_repos\aadpackages\AAD_ExcelChecker\venv\Scripts\python37.dll
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: Getting version from python binary BSS
 WARN 2018-09-11T15:46:17Z: benfred_read_process_memory: copy_address failed for 7ff613404000: Os { code: 299, kind: Other, message: "Only part of a ReadProcessMemory or WriteProcessMemory request was completed." }
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
 INFO 2018-09-11T15:46:17Z: py_spy::python_spy: Failed to connect to process, retrying. Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (os error 299)
version: 0.0.0.0 -> branch: local
```

**Comment by benfred** [comment]
@jergo For the last problem, how long does the python process take to run? Based off the logs, it looks like the python process might have exited before py-spy finished initializing

**Comment by wailashi** [comment]
@benfred using a 64 bit python works. Thanks!

**Comment by benfred** [comment]
I added some logging in the latest version (0.1.6) to warn if it's a 32 bit python detected on windows. I've also disabled generating the i686 windows wheels, which didn't work properly - and I think were the source of most of the errors here =(.

If anyone still see's this issue with the latest version let me know!

**Comment by asypost** [comment]
@benfred The new version(0.1.6) works.Thanks.
