### ISSUE TITLE
Better Idle Detection

### ISSUE THREAD

**Issue by benfred** [benfred/py-spy#92]
The current method of marking a thread as idle is based on some heuristics - which don't work in many cases (ie, time.sleep calls can be marked as active, making it hard to view real profile data https://github.com/benfred/py-spy/issues/87).

With the latest code changes to profile native extensions we have the ability to match the OS thread with the python thread id - meaning that we should be able to figure out from the OS if the thread is idle.

**Comment by njsmith** [comment]
I'm hitting this with 0.2.0.dev1 – py-spy is telling me that my program's spending lots of time in `epoll_wait`, which is probably true, but not very useful :-)

**Comment by dimaqq** [comment]
Let's add `concurrent/futures/thread.py#L78: work_queue.get(block=True)`

**Comment by benfred** [comment]
This PR mostly fixes this issue https://github.com/benfred/py-spy/pull/123 , by matching up the OS thread to the python thread - and then getting thread activity from the OS. 

There are a couple of caveats worth pointing out:
 * we're still using the heuristic method as a fallback for x86/ARM procesesors, or if we can't get the OS threadid for any reason (on linux this only works on x86_64)
 * We get the thread activity immediately before locking the process (otherwise it's always idle), so this is a little racy

**Comment by benfred** [comment]
Can test this out with ```pip install  py-spy==0.2.0.dev2```
