### ISSUE TITLE
Documentation of `GIL` and `Active`

### ISSUE THREAD

**Issue by liwt31** [benfred/py-spy#95]
At the top of the "top-like" interface, there are two parameters `GIL` and `Active`. I'm sure they must have some particular meaning but it's hard to tell simply from their names. I found no info in the README file. Can anyone give me a hint? I think they're better added to the document.

Thanks in advance! py-spy is a great tool for me.

**Comment by benfred** [comment]
They are the number of active threads (in last time period) and how often the [GIL](https://wiki.python.org/moin/GlobalInterpreterLock) was locked. 

Note: Getting the GIL requires certain symbols to be included with your python interpreter right now.

**Comment by liwt31** [comment]
Thanks for the explanation! May I add them to the README file?

**Comment by nlevitt** [comment]
Firstly I'd like to say, it's awesome that py-spy reports these numbers. I'd like to understand better what they mean. I found this in the code:
```
            if trace.owns_gil {
                self.stats.gil += 1
            }
```
```
        out!("GIL: {:.2}%, Active: {:>.2}%, Threads: {}",
            style(100.0 * self.stats.gil as f64 / self.stats.current_samples as f64).bold(),
            style(100.0 * self.stats.active as f64 / self.stats.current_samples as f64).bold(),
            style(self.stats.threads).bold());
```
Does this mean that the GIL number is the percentage of samples in the last second where one of the threads owned the GIL?

If so, that's certainly useful and interesting. But there's so much more I want to know about the GIL. :) Like which threads and functions are holding the GIL and for how long, and which ones are _waiting_ for the GIL and for how long, etc. I guess I should file a new issue for this. It's probably a lot to ask for. 

> Note: Getting the GIL requires certain symbols to be included with your python interpreter right now.

I'm very curious to know more about this. It seems that I am getting GIL information with python 3.7 on macOS, but not with python 3.5 on ubuntu xenial 16.04

**Comment by benfred** [comment]
Added some documentation to the README https://github.com/benfred/py-spy/#how-do-you-detect-if-a-thread-is-idle-or-not and https://github.com/benfred/py-spy/#how-does-gil-detection-work
