### ISSUE TITLE
How to profile with pipe?

### ISSUE THREAD

**Issue by alok** [benfred/py-spy#99]
I'm trying to do something like `grep pattern files | py-spy -- python script.py` to profile `script.py`. It needs to read stdin from the pipe, but instead it seems to finish immediately.

**Comment by benfred** [comment]
Hmm - if I understand correctly, you want the profiled python process to read from stdin, but the pipe you are creating goes to py-spy's stdin instead.

The only way to do this right now is probably to create the python process yourself ```grep pattern files | python script.py``` and then get the PID and go ```py-spy --pid PID``` to profile.

**Comment by alok** [comment]
The process is pretty short lived, so I guess I'll have to script it then. Thanks.
